// GET   /api/v1/bar/supplier-invoices        GET   /api/v1/club/supplier-invoices
// POST  /api/v1/bar/supplier-invoices        POST  /api/v1/club/supplier-invoices
// PATCH /api/v1/bar/supplier-invoices/:id/approve
// PATCH /api/v1/bar/supplier-invoices/:id/pay
//
// Venue (BAR|CLUB) is injected by the mounting router — callers never send it.

import { Router, type Request, type Response, type NextFunction } from 'express';
import { z } from 'zod';
import { withTenantRLS } from '../../middleware/rls';
import { entertainmentPool, corePool } from '../../db/index';
import { logger } from '../../lib/logger';
import { ok, err } from '../../lib/response';
import { type Venue } from './utilities';

const UUIDParam   = z.object({ id: z.string().uuid() });
const VatCodeEnum = z.enum(['STANDARD', 'ZERO', 'EXEMPT']);

const InvoicesQuerySchema = z.object({
  status: z.enum(['RECEIVED', 'APPROVED', 'PAID']).optional(),
  page:   z.coerce.number().int().min(1).default(1),
  limit:  z.coerce.number().int().min(1).max(100).default(20),
}).strict();

const CreateInvoiceSchema = z.object({
  supplier_name:   z.string().min(1).max(200),
  invoice_ref:     z.string().max(100).optional(),
  invoice_date:    z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'invoice_date must be YYYY-MM-DD'),
  due_date:        z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
  amount:          z.number().min(0),
  vat_amount:      z.number().min(0).default(0),
  vat_code:        VatCodeEnum.default('STANDARD'),
  notes:           z.string().max(2000).optional(),
  idempotency_key: z.string().uuid('idempotency_key must be a UUID generated by the client.'),
}).strict();

const PayInvoiceSchema = z.object({
  paid_date:         z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'paid_date must be YYYY-MM-DD'),
  payment_reference: z.string().max(200).optional(),
}).strict();

async function auditLog(tenantId: string, userId: string, action: string, recordId: string, data: unknown): Promise<void> {
  const client = await corePool.connect();
  try {
    await client.query('BEGIN');
    await client.query('SELECT set_config($1, $2, true)', ['app.current_tenant_id', tenantId]);
    await client.query('SELECT set_config($1, $2, true)', ['app.current_user_id', userId]);
    await client.query(
      `INSERT INTO audit_log (tenant_id, user_id, entity, action, record_id, new_values, source)
       VALUES ($1, $2, 'EntSupplierInvoice', $3, $4, $5, 'API')`,
      [tenantId, userId, action, recordId, JSON.stringify(data)],
    );
    await client.query('COMMIT');
  } catch (e) {
    await client.query('ROLLBACK');
    logger.warn({ entity: 'ENT', action: 'AUDIT_LOG_FAILED', error_message: (e as Error).message });
  } finally { client.release(); }
}

export function makeSupplierInvoicesRouter(venue: Venue): Router {
  const router = Router();

  // GET /supplier-invoices
  router.get('/', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      const queryParsed = InvoicesQuerySchema.safeParse(req.query);
      if (!queryParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Invalid query parameters.'); return; }

      const { status, page, limit } = queryParsed.data;
      const offset = (page - 1) * limit;

      const client = await entertainmentPool.connect();
      try {
        const { rows, total } = await withTenantRLS(client, req.rlsCtx, async (c) => {
          const params: unknown[] = [venue];
          const push = (v: unknown) => { params.push(v); return `$${params.length}`; };
          const conditions = ['venue = $1'];
          if (status) conditions.push(`status = ${push(status)}`);
          const where = conditions.join(' AND ');

          const countResult = await c.query<{ count: string }>(
            `SELECT count(*) FROM ent_supplier_invoices WHERE ${where}`, params,
          );
          const dataResult = await c.query(
            `SELECT id, venue, supplier_name, invoice_ref, invoice_date, due_date,
                    amount, vat_code, vat_amount, status,
                    approved_by, approved_at, paid_date, payment_reference,
                    notes, idempotency_key, created_at, updated_at
             FROM   ent_supplier_invoices
             WHERE  ${where}
             ORDER  BY invoice_date DESC
             LIMIT  ${push(limit)} OFFSET ${push(offset)}`,
            params,
          );
          return { rows: dataResult.rows, total: Number(countResult.rows[0].count) };
        });

        logger.info({ entity: 'ENT', action: 'SUPPLIER_INVOICES_LIST', venue, user_id: req.rlsCtx.userId, tenant_id: req.rlsCtx.tenantId, count: rows.length });
        ok(res, { supplier_invoices: rows, pagination: { page, limit, total, pages: Math.ceil(total / limit) } });
      } finally { client.release(); }
    } catch (e) { next(e); }
  });

  // POST /supplier-invoices
  router.post('/', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      const bodyParsed = CreateInvoiceSchema.safeParse(req.body);
      if (!bodyParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Request body validation failed.'); return; }

      const body = bodyParsed.data;
      const { userId, tenantId } = req.rlsCtx;

      const client = await entertainmentPool.connect();
      try {
        const { invoice, created } = await withTenantRLS(client, req.rlsCtx, async (c) => {
          const existing = await c.query<{ id: string }>(
            `SELECT id FROM ent_supplier_invoices WHERE idempotency_key = $1`, [body.idempotency_key],
          );
          if (existing.rows.length > 0) {
            const dup = await c.query(`SELECT * FROM ent_supplier_invoices WHERE id = $1`, [existing.rows[0].id]);
            return { invoice: dup.rows[0], created: false };
          }

          const result = await c.query(
            `INSERT INTO ent_supplier_invoices
               (tenant_id, venue, supplier_name, invoice_ref, invoice_date, due_date,
                amount, vat_code, vat_amount, notes, idempotency_key, created_by)
             VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
             RETURNING *`,
            [
              tenantId, venue,
              body.supplier_name, body.invoice_ref ?? null,
              body.invoice_date, body.due_date ?? null,
              body.amount, body.vat_code, body.vat_amount,
              body.notes ?? null, body.idempotency_key, userId,
            ],
          );
          return { invoice: result.rows[0], created: true };
        });

        logger.info({ entity: 'ENT', action: created ? 'SUPPLIER_INVOICE_CREATED' : 'SUPPLIER_INVOICE_DUPLICATE', venue, user_id: userId, tenant_id: tenantId, record_id: invoice.id });
        if (created) await auditLog(tenantId, userId, 'CREATE', invoice.id, body);
        ok(res, invoice, created ? 201 : 200);
      } finally { client.release(); }
    } catch (e) { next(e); }
  });

  // PATCH /supplier-invoices/:id/approve
  router.patch('/:id/approve', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      const paramParsed = UUIDParam.safeParse(req.params);
      if (!paramParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Invoice ID must be a valid UUID.'); return; }

      const { id } = paramParsed.data;
      const { userId, tenantId } = req.rlsCtx;

      const client = await entertainmentPool.connect();
      try {
        const updated = await withTenantRLS(client, req.rlsCtx, (c) =>
          c.query(
            `UPDATE ent_supplier_invoices
             SET    status      = 'APPROVED',
                    approved_by = $1,
                    approved_at = now(),
                    updated_at  = now()
             WHERE  id = $2
               AND  venue = $3
               AND  status = 'RECEIVED'
             RETURNING *`,
            [userId, id, venue],
          ).then(r => r.rows[0] ?? null),
        );

        if (!updated) { err(res, 404, 'INVOICE_NOT_FOUND', 'Invoice not found or not in RECEIVED status.'); return; }
        logger.info({ entity: 'ENT', action: 'SUPPLIER_INVOICE_APPROVED', venue, user_id: userId, tenant_id: tenantId, record_id: id });
        await auditLog(tenantId, userId, 'APPROVE', id, { status: 'APPROVED' });
        ok(res, updated);
      } finally { client.release(); }
    } catch (e) { next(e); }
  });

  // PATCH /supplier-invoices/:id/pay
  router.patch('/:id/pay', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      const paramParsed = UUIDParam.safeParse(req.params);
      if (!paramParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Invoice ID must be a valid UUID.'); return; }

      const bodyParsed = PayInvoiceSchema.safeParse(req.body);
      if (!bodyParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Request body validation failed.'); return; }

      const { id } = paramParsed.data;
      const { paid_date, payment_reference } = bodyParsed.data;
      const { userId, tenantId } = req.rlsCtx;

      const client = await entertainmentPool.connect();
      try {
        const updated = await withTenantRLS(client, req.rlsCtx, (c) =>
          c.query(
            `UPDATE ent_supplier_invoices
             SET    status            = 'PAID',
                    paid_date         = $1,
                    payment_reference = $2,
                    updated_at        = now()
             WHERE  id = $3
               AND  venue = $4
               AND  status = 'APPROVED'
             RETURNING *`,
            [paid_date, payment_reference ?? null, id, venue],
          ).then(r => r.rows[0] ?? null),
        );

        if (!updated) { err(res, 404, 'INVOICE_NOT_FOUND', 'Invoice not found or not in APPROVED status.'); return; }
        logger.info({ entity: 'ENT', action: 'SUPPLIER_INVOICE_PAID', venue, user_id: userId, tenant_id: tenantId, record_id: id });
        await auditLog(tenantId, userId, 'PAY', id, { paid_date, payment_reference });
        ok(res, updated);
      } finally { client.release(); }
    } catch (e) { next(e); }
  });

  return router;
}
