// GET  /api/v1/bar/utilities        GET  /api/v1/club/utilities
// POST /api/v1/bar/utilities        POST /api/v1/club/utilities
//
// Venue (BAR|CLUB) is injected by the mounting router — callers never send it.

import { Router, type Request, type Response, type NextFunction } from 'express';
import { z } from 'zod';
import { withTenantRLS } from '../../middleware/rls';
import { entertainmentPool, corePool } from '../../db/index';
import { logger } from '../../lib/logger';
import { ok, err } from '../../lib/response';

export type Venue = 'BAR' | 'CLUB';

const VatCodeEnum     = z.enum(['STANDARD', 'ZERO', 'EXEMPT']);
const UtilityTypeEnum = z.enum(['ELECTRICITY', 'WATER', 'GAS', 'INTERNET', 'OTHER']);

const UtilitiesQuerySchema = z.object({
  utility_type: UtilityTypeEnum.optional(),
  page:  z.coerce.number().int().min(1).default(1),
  limit: z.coerce.number().int().min(1).max(100).default(20),
}).strict();

const CreateUtilitySchema = z.object({
  utility_type:    UtilityTypeEnum,
  provider:        z.string().min(1).max(200),
  bill_date:       z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'bill_date must be YYYY-MM-DD'),
  paid_date:       z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
  amount:          z.number().min(0),
  vat_amount:      z.number().min(0).default(0),
  vat_code:        VatCodeEnum.default('STANDARD'),
  notes:           z.string().max(2000).optional(),
  idempotency_key: z.string().uuid('idempotency_key must be a UUID generated by the client.'),
}).strict();

async function auditLog(tenantId: string, userId: string, action: string, recordId: string, data: unknown): Promise<void> {
  const client = await corePool.connect();
  try {
    await client.query('BEGIN');
    await client.query('SELECT set_config($1, $2, true)', ['app.current_tenant_id', tenantId]);
    await client.query('SELECT set_config($1, $2, true)', ['app.current_user_id', userId]);
    await client.query(
      `INSERT INTO audit_log (tenant_id, user_id, entity, action, record_id, new_values, source)
       VALUES ($1, $2, 'EntUtilityBill', $3, $4, $5, 'API')`,
      [tenantId, userId, action, recordId, JSON.stringify(data)],
    );
    await client.query('COMMIT');
  } catch (e) {
    await client.query('ROLLBACK');
    logger.warn({ entity: 'ENT', action: 'AUDIT_LOG_FAILED', error_message: (e as Error).message });
  } finally { client.release(); }
}

export function makeUtilitiesRouter(venue: Venue): Router {
  const router = Router();

  // GET /utilities
  router.get('/', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      const queryParsed = UtilitiesQuerySchema.safeParse(req.query);
      if (!queryParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Invalid query parameters.'); return; }

      const { utility_type, page, limit } = queryParsed.data;
      const offset = (page - 1) * limit;

      const client = await entertainmentPool.connect();
      try {
        const { rows, total } = await withTenantRLS(client, req.rlsCtx, async (c) => {
          const params: unknown[] = [venue];
          const push = (v: unknown) => { params.push(v); return `$${params.length}`; };
          const conditions = ['venue = $1'];
          if (utility_type) conditions.push(`utility_type = ${push(utility_type)}`);
          const where = conditions.join(' AND ');

          const countResult = await c.query<{ count: string }>(
            `SELECT count(*) FROM ent_utility_bills WHERE ${where}`, params,
          );
          const dataResult = await c.query(
            `SELECT id, venue, utility_type, provider, bill_date, paid_date,
                    amount, vat_code, vat_amount, notes, idempotency_key, created_at, updated_at
             FROM   ent_utility_bills
             WHERE  ${where}
             ORDER  BY bill_date DESC
             LIMIT  ${push(limit)} OFFSET ${push(offset)}`,
            params,
          );
          return { rows: dataResult.rows, total: Number(countResult.rows[0].count) };
        });

        logger.info({ entity: 'ENT', action: 'UTILITIES_LIST', venue, user_id: req.rlsCtx.userId, tenant_id: req.rlsCtx.tenantId, count: rows.length });
        ok(res, { utility_bills: rows, pagination: { page, limit, total, pages: Math.ceil(total / limit) } });
      } finally { client.release(); }
    } catch (e) { next(e); }
  });

  // POST /utilities
  router.post('/', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      const bodyParsed = CreateUtilitySchema.safeParse(req.body);
      if (!bodyParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Request body validation failed.'); return; }

      const body = bodyParsed.data;
      const { userId, tenantId } = req.rlsCtx;

      const client = await entertainmentPool.connect();
      try {
        const { bill, created } = await withTenantRLS(client, req.rlsCtx, async (c) => {
          const existing = await c.query<{ id: string }>(
            `SELECT id FROM ent_utility_bills WHERE idempotency_key = $1`, [body.idempotency_key],
          );
          if (existing.rows.length > 0) {
            const dup = await c.query(`SELECT * FROM ent_utility_bills WHERE id = $1`, [existing.rows[0].id]);
            return { bill: dup.rows[0], created: false };
          }

          const result = await c.query(
            `INSERT INTO ent_utility_bills
               (tenant_id, venue, utility_type, provider, bill_date, paid_date,
                amount, vat_code, vat_amount, notes, idempotency_key, created_by)
             VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
             RETURNING *`,
            [
              tenantId, venue, body.utility_type, body.provider,
              body.bill_date, body.paid_date ?? null,
              body.amount, body.vat_code, body.vat_amount,
              body.notes ?? null, body.idempotency_key, userId,
            ],
          );
          return { bill: result.rows[0], created: true };
        });

        logger.info({ entity: 'ENT', action: created ? 'UTILITY_BILL_CREATED' : 'UTILITY_BILL_DUPLICATE', venue, user_id: userId, tenant_id: tenantId, record_id: bill.id });
        if (created) await auditLog(tenantId, userId, 'CREATE', bill.id, body);
        ok(res, bill, created ? 201 : 200);
      } finally { client.release(); }
    } catch (e) { next(e); }
  });

  return router;
}
