// GET   /api/v1/jabco/projects/:projectId/vendor-invoices
// POST  /api/v1/jabco/projects/:projectId/vendor-invoices
// PATCH /api/v1/jabco/projects/:projectId/vendor-invoices/:id/approve
// PATCH /api/v1/jabco/projects/:projectId/vendor-invoices/:id/pay

import { Router, type Request, type Response, type NextFunction } from 'express';
import { z } from 'zod';
import { withTenantRLS } from '../../middleware/rls';
import { commercialPool, corePool } from '../../db/index';
import { logger } from '../../lib/logger';
import { ok, err } from '../../lib/response';

export const jabcoVendorInvoicesRouter = Router({ mergeParams: true });

// ── Schemas ───────────────────────────────────────────────────────────────────

const ProjectParam  = z.object({ projectId: z.string().uuid() });
const InvoiceParam  = z.object({ projectId: z.string().uuid(), id: z.string().uuid() });
const VatCodeEnum   = z.enum(['STANDARD', 'ZERO', 'EXEMPT']);
const VendorTypeEnum = z.enum(['SUPPLIER', 'SUBCONTRACTOR']);

const InvoicesQuerySchema = z.object({
  status:      z.enum(['RECEIVED', 'APPROVED', 'PAID']).optional(),
  vendor_type: VendorTypeEnum.optional(),
  page:        z.coerce.number().int().min(1).default(1),
  limit:       z.coerce.number().int().min(1).max(100).default(20),
}).strict();

const CreateInvoiceSchema = z.object({
  vendor_name:     z.string().min(1).max(200),
  vendor_type:     VendorTypeEnum.default('SUPPLIER'),
  invoice_ref:     z.string().max(100).optional(),
  invoice_date:    z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'invoice_date must be YYYY-MM-DD'),
  due_date:        z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
  amount:          z.number().min(0),
  vat_amount:      z.number().min(0).default(0),
  vat_code:        VatCodeEnum.default('STANDARD'),
  notes:           z.string().max(2000).optional(),
  idempotency_key: z.string().uuid('idempotency_key must be a UUID generated by the client.'),
}).strict();

const PayInvoiceSchema = z.object({
  paid_date:         z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'paid_date must be YYYY-MM-DD'),
  payment_reference: z.string().max(200).optional(),
}).strict();

// ── Shared audit helper ───────────────────────────────────────────────────────

async function auditLog(tenantId: string, userId: string, entity: string, action: string, recordId: string, newValues: unknown): Promise<void> {
  const client = await corePool.connect();
  try {
    await client.query('BEGIN');
    await client.query('SELECT set_config($1, $2, true)', ['app.current_tenant_id', tenantId]);
    await client.query('SELECT set_config($1, $2, true)', ['app.current_user_id', userId]);
    await client.query(
      `INSERT INTO audit_log (tenant_id, user_id, entity, action, record_id, new_values, source)
       VALUES ($1, $2, $3, $4, $5, $6, 'API')`,
      [tenantId, userId, entity, action, recordId, JSON.stringify(newValues)],
    );
    await client.query('COMMIT');
  } catch (e) {
    await client.query('ROLLBACK');
    logger.warn({ entity: 'JABCO', action: 'AUDIT_LOG_FAILED', error_message: (e as Error).message });
  } finally { client.release(); }
}

// ── GET /:projectId/vendor-invoices ───────────────────────────────────────────

jabcoVendorInvoicesRouter.get('/', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const paramParsed = ProjectParam.safeParse(req.params);
    if (!paramParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Project ID must be a valid UUID.'); return; }

    const queryParsed = InvoicesQuerySchema.safeParse(req.query);
    if (!queryParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Invalid query parameters.'); return; }

    const { projectId } = paramParsed.data;
    const { status, vendor_type, page, limit } = queryParsed.data;
    const offset = (page - 1) * limit;

    const client = await commercialPool.connect();
    try {
      const { rows, total } = await withTenantRLS(client, req.rlsCtx, async (c) => {
        const params: unknown[] = [projectId];
        const push = (v: unknown) => { params.push(v); return `$${params.length}`; };
        const conditions = ['project_id = $1'];
        if (status)      conditions.push(`status      = ${push(status)}`);
        if (vendor_type) conditions.push(`vendor_type = ${push(vendor_type)}`);
        const where = conditions.join(' AND ');

        const countResult = await c.query<{ count: string }>(
          `SELECT count(*) FROM jabco_vendor_invoices WHERE ${where}`, params,
        );
        const dataResult = await c.query(
          `SELECT id, project_id, vendor_name, vendor_type, invoice_ref,
                  invoice_date, due_date, amount, vat_code, vat_amount, status,
                  approved_by, approved_at, paid_date, payment_reference,
                  notes, idempotency_key, created_at, updated_at
           FROM   jabco_vendor_invoices
           WHERE  ${where}
           ORDER  BY invoice_date DESC
           LIMIT  ${push(limit)} OFFSET ${push(offset)}`,
          params,
        );
        return { rows: dataResult.rows, total: Number(countResult.rows[0].count) };
      });

      logger.info({ entity: 'JABCO', action: 'VENDOR_INVOICES_LIST', user_id: req.rlsCtx.userId, tenant_id: req.rlsCtx.tenantId, project_id: projectId, count: rows.length });
      ok(res, { vendor_invoices: rows, pagination: { page, limit, total, pages: Math.ceil(total / limit) } });
    } finally { client.release(); }
  } catch (e) { next(e); }
});

// ── POST /:projectId/vendor-invoices ──────────────────────────────────────────

jabcoVendorInvoicesRouter.post('/', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const paramParsed = ProjectParam.safeParse(req.params);
    if (!paramParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Project ID must be a valid UUID.'); return; }

    const bodyParsed = CreateInvoiceSchema.safeParse(req.body);
    if (!bodyParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Request body validation failed.'); return; }

    const { projectId } = paramParsed.data;
    const body = bodyParsed.data;
    const { userId, tenantId } = req.rlsCtx;

    const client = await commercialPool.connect();
    try {
      const { invoice, created } = await withTenantRLS(client, req.rlsCtx, async (c) => {
        const existing = await c.query<{ id: string }>(
          `SELECT id FROM jabco_vendor_invoices WHERE idempotency_key = $1`, [body.idempotency_key],
        );
        if (existing.rows.length > 0) {
          const dup = await c.query(`SELECT * FROM jabco_vendor_invoices WHERE id = $1`, [existing.rows[0].id]);
          return { invoice: dup.rows[0], created: false };
        }

        // Verify project exists and belongs to this tenant (RLS enforces scope).
        const projCheck = await c.query<{ id: string }>(
          `SELECT id FROM jabco_projects WHERE id = $1`, [projectId],
        );
        if (projCheck.rows.length === 0) throw Object.assign(new Error('PROJECT_NOT_FOUND'), { httpStatus: 404 });

        const result = await c.query(
          `INSERT INTO jabco_vendor_invoices
             (tenant_id, project_id, vendor_name, vendor_type, invoice_ref,
              invoice_date, due_date, amount, vat_code, vat_amount,
              notes, idempotency_key, created_by)
           VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
           RETURNING *`,
          [
            tenantId, projectId,
            body.vendor_name, body.vendor_type, body.invoice_ref ?? null,
            body.invoice_date, body.due_date ?? null,
            body.amount, body.vat_code, body.vat_amount,
            body.notes ?? null, body.idempotency_key, userId,
          ],
        );
        return { invoice: result.rows[0], created: true };
      });

      logger.info({ entity: 'JABCO', action: created ? 'VENDOR_INVOICE_CREATED' : 'VENDOR_INVOICE_DUPLICATE', user_id: userId, tenant_id: tenantId, record_id: invoice.id });
      if (created) await auditLog(tenantId, userId, 'JabcoVendorInvoice', 'CREATE', invoice.id, body);
      ok(res, invoice, created ? 201 : 200);
    } finally { client.release(); }
  } catch (e) { next(e); }
});

// ── PATCH /:projectId/vendor-invoices/:id/approve ─────────────────────────────

jabcoVendorInvoicesRouter.patch('/:id/approve', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const paramParsed = InvoiceParam.safeParse(req.params);
    if (!paramParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Invalid path parameters.'); return; }

    const { id, projectId } = paramParsed.data;
    const { userId, tenantId } = req.rlsCtx;

    const client = await commercialPool.connect();
    try {
      const updated = await withTenantRLS(client, req.rlsCtx, (c) =>
        c.query(
          `UPDATE jabco_vendor_invoices
           SET    status      = 'APPROVED',
                  approved_by = $1,
                  approved_at = now(),
                  updated_at  = now()
           WHERE  id = $2
             AND  project_id = $3
             AND  status = 'RECEIVED'
           RETURNING *`,
          [userId, id, projectId],
        ).then(r => r.rows[0] ?? null),
      );

      if (!updated) { err(res, 404, 'INVOICE_NOT_FOUND', 'Invoice not found or not in RECEIVED status.'); return; }
      logger.info({ entity: 'JABCO', action: 'VENDOR_INVOICE_APPROVED', user_id: userId, tenant_id: tenantId, record_id: id });
      await auditLog(tenantId, userId, 'JabcoVendorInvoice', 'APPROVE', id, { status: 'APPROVED' });
      ok(res, updated);
    } finally { client.release(); }
  } catch (e) { next(e); }
});

// ── PATCH /:projectId/vendor-invoices/:id/pay ─────────────────────────────────

jabcoVendorInvoicesRouter.patch('/:id/pay', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const paramParsed = InvoiceParam.safeParse(req.params);
    if (!paramParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Invalid path parameters.'); return; }

    const bodyParsed = PayInvoiceSchema.safeParse(req.body);
    if (!bodyParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Request body validation failed.'); return; }

    const { id, projectId } = paramParsed.data;
    const { paid_date, payment_reference } = bodyParsed.data;
    const { userId, tenantId } = req.rlsCtx;

    const client = await commercialPool.connect();
    try {
      const updated = await withTenantRLS(client, req.rlsCtx, (c) =>
        c.query(
          `UPDATE jabco_vendor_invoices
           SET    status            = 'PAID',
                  paid_date         = $1,
                  payment_reference = $2,
                  updated_at        = now()
           WHERE  id = $3
             AND  project_id = $4
             AND  status = 'APPROVED'
           RETURNING *`,
          [paid_date, payment_reference ?? null, id, projectId],
        ).then(r => r.rows[0] ?? null),
      );

      if (!updated) { err(res, 404, 'INVOICE_NOT_FOUND', 'Invoice not found or not in APPROVED status.'); return; }
      logger.info({ entity: 'JABCO', action: 'VENDOR_INVOICE_PAID', user_id: userId, tenant_id: tenantId, record_id: id });
      await auditLog(tenantId, userId, 'JabcoVendorInvoice', 'PAY', id, { paid_date, payment_reference });
      ok(res, updated);
    } finally { client.release(); }
  } catch (e) { next(e); }
});
