// GET    /api/v1/properties/:propertyId/vendor-invoices
// POST   /api/v1/properties/:propertyId/vendor-invoices
// PATCH  /api/v1/properties/:propertyId/vendor-invoices/:id/approve
// PATCH  /api/v1/properties/:propertyId/vendor-invoices/:id/pay
// GET    /api/v1/properties/:propertyId/vendor-invoices/:id/allocations
// POST   /api/v1/properties/:propertyId/vendor-invoices/:id/allocations — replaces existing allocations
// DELETE /api/v1/properties/:propertyId/vendor-invoices/:id/allocations

import { Router, type Request, type Response, type NextFunction } from 'express';
import { z } from 'zod';
import { withOwnerRLS } from '../../middleware/rls';
import { propertiesPool, corePool } from '../../db/index';
import { logger } from '../../lib/logger';
import { ok, err } from '../../lib/response';

export const vendorInvoicesRouter = Router({ mergeParams: true });

// ── Schemas ───────────────────────────────────────────────────────────────────

const PropertyParam = z.object({ propertyId: z.string().uuid() });
const InvoiceParam  = z.object({ propertyId: z.string().uuid(), id: z.string().uuid() });
const VatCodeEnum   = z.enum(['STANDARD', 'ZERO', 'EXEMPT']);

const InvoicesQuerySchema = z.object({
  status: z.enum(['RECEIVED', 'APPROVED', 'PAID']).optional(),
  page:   z.coerce.number().int().min(1).default(1),
  limit:  z.coerce.number().int().min(1).max(100).default(20),
}).strict();

const CreateInvoiceSchema = z.object({
  vendor_name:            z.string().min(1).max(200),
  invoice_ref:            z.string().max(100).optional(),
  invoice_date:           z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'invoice_date must be YYYY-MM-DD'),
  due_date:               z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
  amount:                 z.number().min(0),
  vat_amount:             z.number().min(0).default(0),
  vat_code:               VatCodeEnum.default('STANDARD'),
  maintenance_request_id: z.string().uuid().optional(),
  notes:                  z.string().max(2000).optional(),
  idempotency_key:        z.string().uuid('idempotency_key must be a UUID generated by the client.'),
}).strict();

const PayInvoiceSchema = z.object({
  paid_date:         z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'paid_date must be YYYY-MM-DD'),
  payment_reference: z.string().max(200).optional(),
}).strict();

const AllocateSchema = z.discriminatedUnion('method', [
  z.object({
    method:   z.literal('EQUAL'),
    unit_ids: z.array(z.string().uuid()).min(1),
  }).strict(),
  z.object({
    method:      z.literal('PERCENTAGE'),
    allocations: z.array(z.object({
      unit_id: z.string().uuid(),
      pct:     z.number().positive().max(100),
    })).min(1),
  }).strict(),
]);

// Splits `total` across `n` shares by percentage without floating-point drift:
// every share but the last is floor-rounded to cents, the last absorbs the
// remainder so the shares always sum to exactly `total`.
function distributeByPct(total: number, pcts: number[]): number[] {
  const cents = Math.round(total * 100);
  const shares: number[] = [];
  let remaining = cents;
  for (let i = 0; i < pcts.length; i++) {
    if (i === pcts.length - 1) {
      shares.push(remaining);
    } else {
      const share = Math.round((cents * pcts[i]) / 100);
      shares.push(share);
      remaining -= share;
    }
  }
  return shares.map(c => c / 100);
}

// ── Shared audit helper ───────────────────────────────────────────────────────

async function auditLog(ownerId: string, entity: string, action: string, recordId: string, newValues: unknown): Promise<void> {
  const client = await corePool.connect();
  try {
    await client.query('BEGIN');
    await client.query('SELECT set_config($1, $2, true)', ['app.current_user_id', ownerId]);
    await client.query(
      `INSERT INTO audit_log (user_id, entity, action, record_id, new_values, source)
       VALUES ($1, $2, $3, $4, $5, 'API')`,
      [ownerId, entity, action, recordId, JSON.stringify(newValues)],
    );
    await client.query('COMMIT');
  } catch (e) {
    await client.query('ROLLBACK');
    logger.warn({ entity: 'PROPERTIES', action: 'AUDIT_LOG_FAILED', error_message: (e as Error).message });
  } finally { client.release(); }
}

// ── GET /:propertyId/vendor-invoices ──────────────────────────────────────────

vendorInvoicesRouter.get('/', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const paramParsed = PropertyParam.safeParse(req.params);
    if (!paramParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Property ID must be a valid UUID.'); return; }

    const queryParsed = InvoicesQuerySchema.safeParse(req.query);
    if (!queryParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Invalid query parameters.'); return; }

    const { propertyId } = paramParsed.data;
    const { status, page, limit } = queryParsed.data;
    const offset = (page - 1) * limit;

    const client = await propertiesPool.connect();
    try {
      const { rows, total } = await withOwnerRLS(client, req.rlsCtx, async (c) => {
        const params: unknown[] = [propertyId];
        const push = (v: unknown) => { params.push(v); return `$${params.length}`; };
        const conditions = ['property_id = $1'];
        if (status) conditions.push(`status = ${push(status)}`);
        const where = conditions.join(' AND ');

        const countResult = await c.query<{ count: string }>(
          `SELECT count(*) FROM prop_vendor_invoices WHERE ${where}`, params,
        );
        const dataResult = await c.query(
          `SELECT id, property_id, maintenance_request_id, vendor_name, invoice_ref,
                  invoice_date, due_date, amount, vat_code, vat_amount, status,
                  approved_by, approved_at, paid_date, payment_reference,
                  notes, idempotency_key, created_at, updated_at
           FROM   prop_vendor_invoices
           WHERE  ${where}
           ORDER  BY invoice_date DESC
           LIMIT  ${push(limit)} OFFSET ${push(offset)}`,
          params,
        );
        return { rows: dataResult.rows, total: Number(countResult.rows[0].count) };
      });

      logger.info({ entity: 'PROPERTIES', action: 'VENDOR_INVOICES_LIST', user_id: req.rlsCtx.userId, property_id: propertyId, count: rows.length });
      ok(res, { vendor_invoices: rows, pagination: { page, limit, total, pages: Math.ceil(total / limit) } });
    } finally { client.release(); }
  } catch (e) { next(e); }
});

// ── POST /:propertyId/vendor-invoices ─────────────────────────────────────────

vendorInvoicesRouter.post('/', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const paramParsed = PropertyParam.safeParse(req.params);
    if (!paramParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Property ID must be a valid UUID.'); return; }

    const bodyParsed = CreateInvoiceSchema.safeParse(req.body);
    if (!bodyParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Request body validation failed.'); return; }

    const { propertyId } = paramParsed.data;
    const body = bodyParsed.data;
    const { userId: ownerId } = req.rlsCtx;

    const client = await propertiesPool.connect();
    try {
      const { invoice, created } = await withOwnerRLS(client, req.rlsCtx, async (c) => {
        const existing = await c.query<{ id: string }>(
          `SELECT id FROM prop_vendor_invoices WHERE idempotency_key = $1`, [body.idempotency_key],
        );
        if (existing.rows.length > 0) {
          const dup = await c.query(`SELECT * FROM prop_vendor_invoices WHERE id = $1`, [existing.rows[0].id]);
          return { invoice: dup.rows[0], created: false };
        }

        const propCheck = await c.query<{ id: string }>(
          `SELECT id FROM prop_properties WHERE id = $1`, [propertyId],
        );
        if (propCheck.rows.length === 0) throw Object.assign(new Error('PROPERTY_NOT_FOUND'), { httpStatus: 404 });

        const result = await c.query(
          `INSERT INTO prop_vendor_invoices
             (owner_id, property_id, maintenance_request_id, vendor_name, invoice_ref,
              invoice_date, due_date, amount, vat_code, vat_amount,
              notes, idempotency_key, created_by)
           VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
           RETURNING *`,
          [
            ownerId, propertyId,
            body.maintenance_request_id ?? null,
            body.vendor_name, body.invoice_ref ?? null,
            body.invoice_date, body.due_date ?? null,
            body.amount, body.vat_code, body.vat_amount,
            body.notes ?? null, body.idempotency_key, ownerId,
          ],
        );
        return { invoice: result.rows[0], created: true };
      });

      logger.info({ entity: 'PROPERTIES', action: created ? 'VENDOR_INVOICE_CREATED' : 'VENDOR_INVOICE_DUPLICATE', user_id: ownerId, record_id: invoice.id });
      if (created) await auditLog(ownerId, 'VendorInvoice', 'CREATE', invoice.id, body);
      ok(res, invoice, created ? 201 : 200);
    } finally { client.release(); }
  } catch (e) { next(e); }
});

// ── PATCH /:propertyId/vendor-invoices/:id/approve ────────────────────────────

vendorInvoicesRouter.patch('/:id/approve', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const paramParsed = InvoiceParam.safeParse(req.params);
    if (!paramParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Invalid path parameters.'); return; }

    const { id, propertyId } = paramParsed.data;
    const { userId: ownerId } = req.rlsCtx;

    const client = await propertiesPool.connect();
    try {
      const updated = await withOwnerRLS(client, req.rlsCtx, (c) =>
        c.query(
          `UPDATE prop_vendor_invoices
           SET    status      = 'APPROVED',
                  approved_by = $1,
                  approved_at = now(),
                  updated_at  = now()
           WHERE  id = $2
             AND  property_id = $3
             AND  status = 'RECEIVED'
           RETURNING *`,
          [ownerId, id, propertyId],
        ).then(r => r.rows[0] ?? null),
      );

      if (!updated) { err(res, 404, 'INVOICE_NOT_FOUND', 'Invoice not found or not in RECEIVED status.'); return; }
      logger.info({ entity: 'PROPERTIES', action: 'VENDOR_INVOICE_APPROVED', user_id: ownerId, record_id: id });
      await auditLog(ownerId, 'VendorInvoice', 'APPROVE', id, { status: 'APPROVED' });
      ok(res, updated);
    } finally { client.release(); }
  } catch (e) { next(e); }
});

// ── PATCH /:propertyId/vendor-invoices/:id/pay ────────────────────────────────

vendorInvoicesRouter.patch('/:id/pay', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const paramParsed = InvoiceParam.safeParse(req.params);
    if (!paramParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Invalid path parameters.'); return; }

    const bodyParsed = PayInvoiceSchema.safeParse(req.body);
    if (!bodyParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Request body validation failed.'); return; }

    const { id, propertyId } = paramParsed.data;
    const { paid_date, payment_reference } = bodyParsed.data;
    const { userId: ownerId } = req.rlsCtx;

    const client = await propertiesPool.connect();
    try {
      const updated = await withOwnerRLS(client, req.rlsCtx, (c) =>
        c.query(
          `UPDATE prop_vendor_invoices
           SET    status            = 'PAID',
                  paid_date         = $1,
                  payment_reference = $2,
                  updated_at        = now()
           WHERE  id = $3
             AND  property_id = $4
             AND  status = 'APPROVED'
           RETURNING *`,
          [paid_date, payment_reference ?? null, id, propertyId],
        ).then(r => r.rows[0] ?? null),
      );

      if (!updated) { err(res, 404, 'INVOICE_NOT_FOUND', 'Invoice not found or not in APPROVED status.'); return; }
      logger.info({ entity: 'PROPERTIES', action: 'VENDOR_INVOICE_PAID', user_id: ownerId, record_id: id });
      await auditLog(ownerId, 'VendorInvoice', 'PAY', id, { paid_date, payment_reference });
      ok(res, updated);
    } finally { client.release(); }
  } catch (e) { next(e); }
});

// ── GET /:propertyId/vendor-invoices/:id/allocations ──────────────────────────

vendorInvoicesRouter.get('/:id/allocations', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const paramParsed = InvoiceParam.safeParse(req.params);
    if (!paramParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Invalid path parameters.'); return; }
    const { id, propertyId } = paramParsed.data;

    const client = await propertiesPool.connect();
    try {
      const rows = await withOwnerRLS(client, req.rlsCtx, (c) =>
        c.query(
          `SELECT a.id, a.invoice_id, a.unit_id, a.pct, a.amount, a.created_at, u.unit_number
           FROM   prop_vendor_invoice_allocations a
           JOIN   prop_units u ON u.id = a.unit_id
           JOIN   prop_vendor_invoices i ON i.id = a.invoice_id
           WHERE  a.invoice_id = $1 AND i.property_id = $2
           ORDER  BY u.unit_number`,
          [id, propertyId],
        ).then(r => r.rows),
      );
      ok(res, rows);
    } finally { client.release(); }
  } catch (e) { next(e); }
});

// ── POST /:propertyId/vendor-invoices/:id/allocations — replace allocation set ─

vendorInvoicesRouter.post('/:id/allocations', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const paramParsed = InvoiceParam.safeParse(req.params);
    if (!paramParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Invalid path parameters.'); return; }
    const bodyParsed = AllocateSchema.safeParse(req.body);
    if (!bodyParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Request body validation failed.'); return; }

    const { id, propertyId } = paramParsed.data;
    const body = bodyParsed.data;
    const { userId: ownerId } = req.rlsCtx;

    let unitIds: string[];
    let pcts: number[];
    if (body.method === 'EQUAL') {
      unitIds = body.unit_ids;
      pcts = unitIds.map(() => 100 / unitIds.length);
    } else {
      unitIds = body.allocations.map(a => a.unit_id);
      pcts = body.allocations.map(a => a.pct);
      const pctSum = pcts.reduce((s, p) => s + p, 0);
      if (Math.abs(pctSum - 100) > 0.5) {
        err(res, 422, 'VALIDATION_ERROR', `Percentages must sum to 100 (got ${pctSum.toFixed(2)}).`);
        return;
      }
    }
    if (new Set(unitIds).size !== unitIds.length) {
      err(res, 422, 'VALIDATION_ERROR', 'Each unit can only appear once in an allocation.'); return;
    }

    const client = await propertiesPool.connect();
    try {
      const result = await withOwnerRLS(client, req.rlsCtx, async (c) => {
        const invoice = await c.query<{ amount: string }>(
          `SELECT amount FROM prop_vendor_invoices WHERE id = $1 AND property_id = $2`,
          [id, propertyId],
        ).then(r => r.rows[0] ?? null);
        if (!invoice) throw Object.assign(new Error('INVOICE_NOT_FOUND'), { httpStatus: 404 });

        const unitCheck = await c.query<{ id: string }>(
          `SELECT id FROM prop_units WHERE id = ANY($1::uuid[]) AND property_id = $2`,
          [unitIds, propertyId],
        );
        if (unitCheck.rows.length !== unitIds.length) {
          throw Object.assign(new Error('UNIT_NOT_IN_PROPERTY'), { httpStatus: 422 });
        }

        const amounts = distributeByPct(Number(invoice.amount), pcts);

        await c.query(`DELETE FROM prop_vendor_invoice_allocations WHERE invoice_id = $1`, [id]);

        const inserted = [];
        for (let i = 0; i < unitIds.length; i++) {
          const row = await c.query(
            `INSERT INTO prop_vendor_invoice_allocations (owner_id, invoice_id, unit_id, pct, amount)
             VALUES ($1,$2,$3,$4,$5) RETURNING id, invoice_id, unit_id, pct, amount, created_at`,
            [ownerId, id, unitIds[i], pcts[i], amounts[i]],
          );
          inserted.push(row.rows[0]);
        }
        return inserted;
      });

      logger.info({ entity: 'PROPERTIES', action: 'VENDOR_INVOICE_ALLOCATED', user_id: ownerId, record_id: id, unit_count: unitIds.length });
      await auditLog(ownerId, 'VendorInvoice', 'ALLOCATE', id, { method: body.method, unit_ids: unitIds });
      ok(res, result, 201);
    } finally { client.release(); }
  } catch (e: unknown) {
    const ex = e as { httpStatus?: number; message: string };
    if (ex.httpStatus === 404) { err(res, 404, 'INVOICE_NOT_FOUND', 'Invoice not found.'); return; }
    if (ex.httpStatus === 422) { err(res, 422, 'VALIDATION_ERROR', 'One or more units do not belong to this property.'); return; }
    next(e);
  }
});

// ── DELETE /:propertyId/vendor-invoices/:id/allocations ────────────────────────

vendorInvoicesRouter.delete('/:id/allocations', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const paramParsed = InvoiceParam.safeParse(req.params);
    if (!paramParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Invalid path parameters.'); return; }
    const { id, propertyId } = paramParsed.data;
    const { userId: ownerId } = req.rlsCtx;

    const client = await propertiesPool.connect();
    try {
      const deleted = await withOwnerRLS(client, req.rlsCtx, (c) =>
        c.query(
          `DELETE FROM prop_vendor_invoice_allocations
           WHERE invoice_id = $1
             AND invoice_id IN (SELECT id FROM prop_vendor_invoices WHERE id = $1 AND property_id = $2)
           RETURNING id`,
          [id, propertyId],
        ).then(r => r.rows),
      );
      logger.info({ entity: 'PROPERTIES', action: 'VENDOR_INVOICE_ALLOCATIONS_CLEARED', user_id: ownerId, record_id: id, count: deleted.length });
      ok(res, { invoice_id: id, cleared: deleted.length });
    } finally { client.release(); }
  } catch (e) { next(e); }
});
