// GET   /api/v1/properties/:propertyId/vendor-invoices
// POST  /api/v1/properties/:propertyId/vendor-invoices
// PATCH /api/v1/properties/:propertyId/vendor-invoices/:id/approve
// PATCH /api/v1/properties/:propertyId/vendor-invoices/:id/pay

import { Router, type Request, type Response, type NextFunction } from 'express';
import { z } from 'zod';
import { withOwnerRLS } from '../../middleware/rls';
import { propertiesPool, corePool } from '../../db/index';
import { logger } from '../../lib/logger';
import { ok, err } from '../../lib/response';

export const vendorInvoicesRouter = Router({ mergeParams: true });

// ── Schemas ───────────────────────────────────────────────────────────────────

const PropertyParam = z.object({ propertyId: z.string().uuid() });
const InvoiceParam  = z.object({ propertyId: z.string().uuid(), id: z.string().uuid() });
const VatCodeEnum   = z.enum(['STANDARD', 'ZERO', 'EXEMPT']);

const InvoicesQuerySchema = z.object({
  status: z.enum(['RECEIVED', 'APPROVED', 'PAID']).optional(),
  page:   z.coerce.number().int().min(1).default(1),
  limit:  z.coerce.number().int().min(1).max(100).default(20),
}).strict();

const CreateInvoiceSchema = z.object({
  vendor_name:            z.string().min(1).max(200),
  invoice_ref:            z.string().max(100).optional(),
  invoice_date:           z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'invoice_date must be YYYY-MM-DD'),
  due_date:               z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
  amount:                 z.number().min(0),
  vat_amount:             z.number().min(0).default(0),
  vat_code:               VatCodeEnum.default('STANDARD'),
  maintenance_request_id: z.string().uuid().optional(),
  notes:                  z.string().max(2000).optional(),
  idempotency_key:        z.string().uuid('idempotency_key must be a UUID generated by the client.'),
}).strict();

const PayInvoiceSchema = z.object({
  paid_date:         z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'paid_date must be YYYY-MM-DD'),
  payment_reference: z.string().max(200).optional(),
}).strict();

// ── Shared audit helper ───────────────────────────────────────────────────────

async function auditLog(ownerId: string, entity: string, action: string, recordId: string, newValues: unknown): Promise<void> {
  const client = await corePool.connect();
  try {
    await client.query('BEGIN');
    await client.query('SELECT set_config($1, $2, true)', ['app.current_user_id', ownerId]);
    await client.query(
      `INSERT INTO audit_log (user_id, entity, action, record_id, new_values, source)
       VALUES ($1, $2, $3, $4, $5, 'API')`,
      [ownerId, entity, action, recordId, JSON.stringify(newValues)],
    );
    await client.query('COMMIT');
  } catch (e) {
    await client.query('ROLLBACK');
    logger.warn({ entity: 'PROPERTIES', action: 'AUDIT_LOG_FAILED', error_message: (e as Error).message });
  } finally { client.release(); }
}

// ── GET /:propertyId/vendor-invoices ──────────────────────────────────────────

vendorInvoicesRouter.get('/', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const paramParsed = PropertyParam.safeParse(req.params);
    if (!paramParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Property ID must be a valid UUID.'); return; }

    const queryParsed = InvoicesQuerySchema.safeParse(req.query);
    if (!queryParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Invalid query parameters.'); return; }

    const { propertyId } = paramParsed.data;
    const { status, page, limit } = queryParsed.data;
    const offset = (page - 1) * limit;

    const client = await propertiesPool.connect();
    try {
      const { rows, total } = await withOwnerRLS(client, req.rlsCtx, async (c) => {
        const params: unknown[] = [propertyId];
        const push = (v: unknown) => { params.push(v); return `$${params.length}`; };
        const conditions = ['property_id = $1'];
        if (status) conditions.push(`status = ${push(status)}`);
        const where = conditions.join(' AND ');

        const countResult = await c.query<{ count: string }>(
          `SELECT count(*) FROM prop_vendor_invoices WHERE ${where}`, params,
        );
        const dataResult = await c.query(
          `SELECT id, property_id, maintenance_request_id, vendor_name, invoice_ref,
                  invoice_date, due_date, amount, vat_code, vat_amount, status,
                  approved_by, approved_at, paid_date, payment_reference,
                  notes, idempotency_key, created_at, updated_at
           FROM   prop_vendor_invoices
           WHERE  ${where}
           ORDER  BY invoice_date DESC
           LIMIT  ${push(limit)} OFFSET ${push(offset)}`,
          params,
        );
        return { rows: dataResult.rows, total: Number(countResult.rows[0].count) };
      });

      logger.info({ entity: 'PROPERTIES', action: 'VENDOR_INVOICES_LIST', user_id: req.rlsCtx.userId, property_id: propertyId, count: rows.length });
      ok(res, { vendor_invoices: rows, pagination: { page, limit, total, pages: Math.ceil(total / limit) } });
    } finally { client.release(); }
  } catch (e) { next(e); }
});

// ── POST /:propertyId/vendor-invoices ─────────────────────────────────────────

vendorInvoicesRouter.post('/', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const paramParsed = PropertyParam.safeParse(req.params);
    if (!paramParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Property ID must be a valid UUID.'); return; }

    const bodyParsed = CreateInvoiceSchema.safeParse(req.body);
    if (!bodyParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Request body validation failed.'); return; }

    const { propertyId } = paramParsed.data;
    const body = bodyParsed.data;
    const { userId: ownerId } = req.rlsCtx;

    const client = await propertiesPool.connect();
    try {
      const { invoice, created } = await withOwnerRLS(client, req.rlsCtx, async (c) => {
        const existing = await c.query<{ id: string }>(
          `SELECT id FROM prop_vendor_invoices WHERE idempotency_key = $1`, [body.idempotency_key],
        );
        if (existing.rows.length > 0) {
          const dup = await c.query(`SELECT * FROM prop_vendor_invoices WHERE id = $1`, [existing.rows[0].id]);
          return { invoice: dup.rows[0], created: false };
        }

        const propCheck = await c.query<{ id: string }>(
          `SELECT id FROM prop_properties WHERE id = $1`, [propertyId],
        );
        if (propCheck.rows.length === 0) throw Object.assign(new Error('PROPERTY_NOT_FOUND'), { httpStatus: 404 });

        const result = await c.query(
          `INSERT INTO prop_vendor_invoices
             (owner_id, property_id, maintenance_request_id, vendor_name, invoice_ref,
              invoice_date, due_date, amount, vat_code, vat_amount,
              notes, idempotency_key, created_by)
           VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
           RETURNING *`,
          [
            ownerId, propertyId,
            body.maintenance_request_id ?? null,
            body.vendor_name, body.invoice_ref ?? null,
            body.invoice_date, body.due_date ?? null,
            body.amount, body.vat_code, body.vat_amount,
            body.notes ?? null, body.idempotency_key, ownerId,
          ],
        );
        return { invoice: result.rows[0], created: true };
      });

      logger.info({ entity: 'PROPERTIES', action: created ? 'VENDOR_INVOICE_CREATED' : 'VENDOR_INVOICE_DUPLICATE', user_id: ownerId, record_id: invoice.id });
      if (created) await auditLog(ownerId, 'VendorInvoice', 'CREATE', invoice.id, body);
      ok(res, invoice, created ? 201 : 200);
    } finally { client.release(); }
  } catch (e) { next(e); }
});

// ── PATCH /:propertyId/vendor-invoices/:id/approve ────────────────────────────

vendorInvoicesRouter.patch('/:id/approve', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const paramParsed = InvoiceParam.safeParse(req.params);
    if (!paramParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Invalid path parameters.'); return; }

    const { id, propertyId } = paramParsed.data;
    const { userId: ownerId } = req.rlsCtx;

    const client = await propertiesPool.connect();
    try {
      const updated = await withOwnerRLS(client, req.rlsCtx, (c) =>
        c.query(
          `UPDATE prop_vendor_invoices
           SET    status      = 'APPROVED',
                  approved_by = $1,
                  approved_at = now(),
                  updated_at  = now()
           WHERE  id = $2
             AND  property_id = $3
             AND  status = 'RECEIVED'
           RETURNING *`,
          [ownerId, id, propertyId],
        ).then(r => r.rows[0] ?? null),
      );

      if (!updated) { err(res, 404, 'INVOICE_NOT_FOUND', 'Invoice not found or not in RECEIVED status.'); return; }
      logger.info({ entity: 'PROPERTIES', action: 'VENDOR_INVOICE_APPROVED', user_id: ownerId, record_id: id });
      await auditLog(ownerId, 'VendorInvoice', 'APPROVE', id, { status: 'APPROVED' });
      ok(res, updated);
    } finally { client.release(); }
  } catch (e) { next(e); }
});

// ── PATCH /:propertyId/vendor-invoices/:id/pay ────────────────────────────────

vendorInvoicesRouter.patch('/:id/pay', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const paramParsed = InvoiceParam.safeParse(req.params);
    if (!paramParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Invalid path parameters.'); return; }

    const bodyParsed = PayInvoiceSchema.safeParse(req.body);
    if (!bodyParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Request body validation failed.'); return; }

    const { id, propertyId } = paramParsed.data;
    const { paid_date, payment_reference } = bodyParsed.data;
    const { userId: ownerId } = req.rlsCtx;

    const client = await propertiesPool.connect();
    try {
      const updated = await withOwnerRLS(client, req.rlsCtx, (c) =>
        c.query(
          `UPDATE prop_vendor_invoices
           SET    status            = 'PAID',
                  paid_date         = $1,
                  payment_reference = $2,
                  updated_at        = now()
           WHERE  id = $3
             AND  property_id = $4
             AND  status = 'APPROVED'
           RETURNING *`,
          [paid_date, payment_reference ?? null, id, propertyId],
        ).then(r => r.rows[0] ?? null),
      );

      if (!updated) { err(res, 404, 'INVOICE_NOT_FOUND', 'Invoice not found or not in APPROVED status.'); return; }
      logger.info({ entity: 'PROPERTIES', action: 'VENDOR_INVOICE_PAID', user_id: ownerId, record_id: id });
      await auditLog(ownerId, 'VendorInvoice', 'PAY', id, { paid_date, payment_reference });
      ok(res, updated);
    } finally { client.release(); }
  } catch (e) { next(e); }
});
