// GET    /api/v1/properties/:propertyId/vendor-invoices
// POST   /api/v1/properties/:propertyId/vendor-invoices
// PATCH  /api/v1/properties/:propertyId/vendor-invoices/:id/approve
// PATCH  /api/v1/properties/:propertyId/vendor-invoices/:id/pay
// PATCH  /api/v1/properties/:propertyId/vendor-invoices/:id/unpay
// GET    /api/v1/properties/:propertyId/vendor-invoices/:id/allocations
// POST   /api/v1/properties/:propertyId/vendor-invoices/:id/allocations — replaces existing allocations
// DELETE /api/v1/properties/:propertyId/vendor-invoices/:id/allocations

import { Router, type Request, type Response, type NextFunction } from 'express';
import { z } from 'zod';
import { withOwnerRLS } from '../../middleware/rls';
import { propertiesPool, corePool, familyPool } from '../../db/index';
import { logger } from '../../lib/logger';
import { ok, err } from '../../lib/response';

export const vendorInvoicesRouter = Router({ mergeParams: true });

// JAG Properties entity (jag_core.tenants.id) — owner_entity_id for bridged Finance expenses.
const PROPERTIES_ENTITY_ID = '00000000-0000-0000-0001-000000000003';
// Default Finance expense account for bridged vendor invoices: 5100 Maintenance & Repairs
// (a postable leaf; the 5000 header is not directly postable). The finance reviewer can
// change it on the DRAFT before posting.
const DEFAULT_EXPENSE_ACCOUNT_CODE = '5100';
// Phase 2 (accrual) settlement accounts for the Properties entity's GL.
// Paying an invoice posts Dr 2100 Accounts Payable / Cr 1100 FCB Bank (…3082),
// clearing the payable raised at finance-approval (Dr 5100 / Cr 2100).
const AP_ACCOUNT_CODE   = '2100';
const BANK_ACCOUNT_CODE = '1100';

// ── Schemas ───────────────────────────────────────────────────────────────────

const PropertyParam = z.object({ propertyId: z.string().uuid() });
const InvoiceParam  = z.object({ propertyId: z.string().uuid(), id: z.string().uuid() });
const VatCodeEnum   = z.enum(['STANDARD', 'ZERO', 'EXEMPT']);

const InvoicesQuerySchema = z.object({
  status: z.enum(['RECEIVED', 'APPROVED', 'PAID']).optional(),
  page:   z.coerce.number().int().min(1).default(1),
  limit:  z.coerce.number().int().min(1).max(100).default(20),
}).strict();

const CreateInvoiceSchema = z.object({
  vendor_name:            z.string().min(1).max(200),
  invoice_ref:            z.string().max(100).optional(),
  invoice_date:           z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'invoice_date must be YYYY-MM-DD'),
  due_date:               z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),
  amount:                 z.number().min(0),
  vat_amount:             z.number().min(0).default(0),
  vat_code:               VatCodeEnum.default('STANDARD'),
  maintenance_request_id: z.string().uuid().optional(),
  notes:                  z.string().max(2000).optional(),
  idempotency_key:        z.string().uuid('idempotency_key must be a UUID generated by the client.'),
}).strict();

const PayInvoiceSchema = z.object({
  paid_date:         z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'paid_date must be YYYY-MM-DD'),
  payment_reference: z.string().max(200).optional(),
}).strict();

const UnpayInvoiceSchema = z.object({
  reason: z.string().min(1).max(500),
}).strict();

const AllocateSchema = z.discriminatedUnion('method', [
  z.object({
    method:   z.literal('EQUAL'),
    unit_ids: z.array(z.string().uuid()).min(1),
  }).strict(),
  z.object({
    method:      z.literal('PERCENTAGE'),
    allocations: z.array(z.object({
      unit_id: z.string().uuid(),
      pct:     z.number().positive().max(100),
    })).min(1),
  }).strict(),
]);

// Splits `total` across `n` shares by percentage without floating-point drift:
// every share but the last is floor-rounded to cents, the last absorbs the
// remainder so the shares always sum to exactly `total`.
function distributeByPct(total: number, pcts: number[]): number[] {
  const cents = Math.round(total * 100);
  const shares: number[] = [];
  let remaining = cents;
  for (let i = 0; i < pcts.length; i++) {
    if (i === pcts.length - 1) {
      shares.push(remaining);
    } else {
      const share = Math.round((cents * pcts[i]) / 100);
      shares.push(share);
      remaining -= share;
    }
  }
  return shares.map(c => c / 100);
}

// ── Shared audit helper ───────────────────────────────────────────────────────

async function auditLog(ownerId: string, entity: string, action: string, recordId: string, newValues: unknown): Promise<void> {
  const client = await corePool.connect();
  try {
    await client.query('BEGIN');
    await client.query('SELECT set_config($1, $2, true)', ['app.current_user_id', ownerId]);
    await client.query(
      `INSERT INTO audit_log (user_id, entity, action, record_id, new_values, source)
       VALUES ($1, $2, $3, $4, $5, 'API')`,
      [ownerId, entity, action, recordId, JSON.stringify(newValues)],
    );
    await client.query('COMMIT');
  } catch (e) {
    await client.query('ROLLBACK');
    logger.warn({ entity: 'PROPERTIES', action: 'AUDIT_LOG_FAILED', error_message: (e as Error).message });
  } finally { client.release(); }
}

// ── GET /:propertyId/vendor-invoices ──────────────────────────────────────────

vendorInvoicesRouter.get('/', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const paramParsed = PropertyParam.safeParse(req.params);
    if (!paramParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Property ID must be a valid UUID.'); return; }

    const queryParsed = InvoicesQuerySchema.safeParse(req.query);
    if (!queryParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Invalid query parameters.'); return; }

    const { propertyId } = paramParsed.data;
    const { status, page, limit } = queryParsed.data;
    const offset = (page - 1) * limit;

    const client = await propertiesPool.connect();
    try {
      const { rows, total } = await withOwnerRLS(client, req.rlsCtx, async (c) => {
        const params: unknown[] = [propertyId];
        const push = (v: unknown) => { params.push(v); return `$${params.length}`; };
        const conditions = ['property_id = $1'];
        if (status) conditions.push(`status = ${push(status)}`);
        const where = conditions.join(' AND ');

        const countResult = await c.query<{ count: string }>(
          `SELECT count(*) FROM prop_vendor_invoices WHERE ${where}`, params,
        );
        const dataResult = await c.query(
          `SELECT id, property_id, maintenance_request_id, vendor_name, invoice_ref,
                  invoice_date, due_date, amount, vat_code, vat_amount, status,
                  approved_by, approved_at, paid_date, payment_reference,
                  notes, idempotency_key, linked_expense_id, settlement_journal_entry_id,
                  created_at, updated_at
           FROM   prop_vendor_invoices
           WHERE  ${where}
           ORDER  BY invoice_date DESC
           LIMIT  ${push(limit)} OFFSET ${push(offset)}`,
          params,
        );
        return { rows: dataResult.rows, total: Number(countResult.rows[0].count) };
      });

      logger.info({ entity: 'PROPERTIES', action: 'VENDOR_INVOICES_LIST', user_id: req.rlsCtx.userId, property_id: propertyId, count: rows.length });
      ok(res, { vendor_invoices: rows, pagination: { page, limit, total, pages: Math.ceil(total / limit) } });
    } finally { client.release(); }
  } catch (e) { next(e); }
});

// ── POST /:propertyId/vendor-invoices ─────────────────────────────────────────

vendorInvoicesRouter.post('/', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const paramParsed = PropertyParam.safeParse(req.params);
    if (!paramParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Property ID must be a valid UUID.'); return; }

    const bodyParsed = CreateInvoiceSchema.safeParse(req.body);
    if (!bodyParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Request body validation failed.'); return; }

    const { propertyId } = paramParsed.data;
    const body = bodyParsed.data;
    const { userId: ownerId } = req.rlsCtx;

    const client = await propertiesPool.connect();
    try {
      const { invoice, created } = await withOwnerRLS(client, req.rlsCtx, async (c) => {
        const existing = await c.query<{ id: string }>(
          `SELECT id FROM prop_vendor_invoices WHERE idempotency_key = $1`, [body.idempotency_key],
        );
        if (existing.rows.length > 0) {
          const dup = await c.query(`SELECT * FROM prop_vendor_invoices WHERE id = $1`, [existing.rows[0].id]);
          return { invoice: dup.rows[0], created: false };
        }

        const propCheck = await c.query<{ id: string }>(
          `SELECT id FROM prop_properties WHERE id = $1`, [propertyId],
        );
        if (propCheck.rows.length === 0) throw Object.assign(new Error('PROPERTY_NOT_FOUND'), { httpStatus: 404 });

        const result = await c.query(
          `INSERT INTO prop_vendor_invoices
             (owner_id, property_id, maintenance_request_id, vendor_name, invoice_ref,
              invoice_date, due_date, amount, vat_code, vat_amount,
              notes, idempotency_key, created_by)
           VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
           RETURNING *`,
          [
            ownerId, propertyId,
            body.maintenance_request_id ?? null,
            body.vendor_name, body.invoice_ref ?? null,
            body.invoice_date, body.due_date ?? null,
            body.amount, body.vat_code, body.vat_amount,
            body.notes ?? null, body.idempotency_key, ownerId,
          ],
        );
        return { invoice: result.rows[0], created: true };
      });

      logger.info({ entity: 'PROPERTIES', action: created ? 'VENDOR_INVOICE_CREATED' : 'VENDOR_INVOICE_DUPLICATE', user_id: ownerId, record_id: invoice.id });
      if (created) await auditLog(ownerId, 'VendorInvoice', 'CREATE', invoice.id, body);
      ok(res, invoice, created ? 201 : 200);
    } finally { client.release(); }
  } catch (e) { next(e); }
});

// ── PATCH /:propertyId/vendor-invoices/:id/approve ────────────────────────────

vendorInvoicesRouter.patch('/:id/approve', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const paramParsed = InvoiceParam.safeParse(req.params);
    if (!paramParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Invalid path parameters.'); return; }

    const { id, propertyId } = paramParsed.data;
    const { ownerId, userId } = req.rlsCtx;

    // ── Step 1 — Load the invoice (must be RECEIVED) + its property name ─────────
    const propClient = await propertiesPool.connect();
    let invoice: {
      property_id: string; vendor_name: string; invoice_ref: string | null;
      invoice_date: string; amount: string; vat_amount: string; property_name: string;
    } | null;
    try {
      invoice = await withOwnerRLS(propClient, req.rlsCtx, (c) =>
        c.query(
          `SELECT vi.property_id, vi.vendor_name, vi.invoice_ref,
                  vi.invoice_date::text AS invoice_date, vi.amount, vi.vat_amount,
                  COALESCE(p.name, p.address_line1, 'Property') AS property_name
           FROM   prop_vendor_invoices vi
           JOIN   prop_properties p ON p.id = vi.property_id
           WHERE  vi.id = $1 AND vi.property_id = $2 AND vi.status = 'RECEIVED'`,
          [id, propertyId],
        ).then(r => r.rows[0] ?? null),
      );
    } finally { propClient.release(); }

    if (!invoice) { err(res, 404, 'INVOICE_NOT_FOUND', 'Invoice not found or not in RECEIVED status.'); return; }

    const total = Number(invoice.amount) + Number(invoice.vat_amount);
    const idemKey = `prop-invoice-${id}`;
    const description = `Vendor invoice — ${invoice.vendor_name}${invoice.invoice_ref ? ' #' + invoice.invoice_ref : ''}`;

    // ── Step 2 — Cross-DB: create (idempotently) a linked DRAFT Finance expense ──
    // jag_family.fin_expenses lives in a separate database; this is a compensating
    // cross-DB write (no distributed transaction). The DRAFT is NOT posted to the GL
    // (Phase 1) — the finance reviewer submits/approves it there. linked_record_type
    // 'PROPERTY' ties it to the property; the property portal reads it back by that link.
    const famClient = await familyPool.connect();
    let expenseId: string;
    let wasCreated: boolean;
    try {
      ({ expenseId, wasCreated } = await withOwnerRLS(famClient, req.rlsCtx, async (c) => {
        const acct = await c.query<{ id: string }>(
          `SELECT id FROM fin_gl_accounts
           WHERE owner_entity_id = $1 AND account_code = $2 AND is_active = true`,
          [PROPERTIES_ENTITY_ID, DEFAULT_EXPENSE_ACCOUNT_CODE],
        );
        const debitAccountId = acct.rows[0]?.id ?? null;

        const ins = await c.query<{ id: string }>(
          `INSERT INTO fin_expenses
             (owner_id, owner_entity_id, submitted_by, expense_date, description, payee_name,
              amount, currency, amount_ttd, payment_method, category,
              gl_debit_account_id, notes, idempotency_key,
              linked_record_type, linked_record_id, linked_record_label)
           VALUES ($1,$2,$3,$4,$5,$6,$7,'TTD',$7,'BANK_TRANSFER','MAINTENANCE',
                   $8,$9,$10,'PROPERTY',$11,$12)
           ON CONFLICT (idempotency_key) DO NOTHING
           RETURNING id`,
          [ownerId, PROPERTIES_ENTITY_ID, userId, invoice.invoice_date, description,
           invoice.vendor_name, total, debitAccountId,
           `Bridged from property vendor invoice ${id} (${invoice.property_name}).`,
           idemKey, invoice.property_id, invoice.property_name],
        );
        if (ins.rows[0]) return { expenseId: ins.rows[0].id, wasCreated: true };
        // Idempotency-key already used (a prior partial run) — reuse that expense.
        const existing = await c.query<{ id: string }>(
          `SELECT id FROM fin_expenses WHERE idempotency_key = $1`, [idemKey],
        );
        return { expenseId: existing.rows[0].id, wasCreated: false };
      }));
    } catch (e) {
      logger.error({ entity: 'PROPERTIES', action: 'VENDOR_INVOICE_BRIDGE_FAILED', record_id: id, error: String(e) });
      err(res, 502, 'FINANCE_BRIDGE_FAILED', 'Could not create the linked Finance expense; invoice left unapproved.');
      return;
    } finally { famClient.release(); }

    // ── Step 3 — Approve the invoice + record the link (atomic, guarded) ─────────
    const propClient2 = await propertiesPool.connect();
    let updated: Record<string, unknown> | null;
    try {
      updated = await withOwnerRLS(propClient2, req.rlsCtx, (c) =>
        c.query(
          `UPDATE prop_vendor_invoices
           SET    status            = 'APPROVED',
                  approved_by        = $1,
                  approved_at        = now(),
                  linked_expense_id  = $2,
                  updated_at         = now()
           WHERE  id = $3
             AND  property_id = $4
             AND  status = 'RECEIVED'
           RETURNING *`,
          [userId, expenseId, id, propertyId],
        ).then(r => r.rows[0] ?? null),
      );
    } finally { propClient2.release(); }

    // Race: invoice left RECEIVED status between step 1 and step 3. Compensate by
    // deleting the orphan DRAFT we just created (only if we created it).
    if (!updated) {
      if (wasCreated) {
        const cleanup = await familyPool.connect();
        try {
          await withOwnerRLS(cleanup, req.rlsCtx, (c) =>
            c.query(`DELETE FROM fin_expenses WHERE id = $1 AND status = 'DRAFT'`, [expenseId]),
          );
        } catch (e) {
          logger.warn({ entity: 'PROPERTIES', action: 'VENDOR_INVOICE_BRIDGE_CLEANUP_FAILED', record_id: id, expense_id: expenseId, error: String(e) });
        } finally { cleanup.release(); }
      }
      err(res, 409, 'INVOICE_STATE_CHANGED', 'Invoice was modified concurrently; please retry.');
      return;
    }

    logger.info({ entity: 'PROPERTIES', action: 'VENDOR_INVOICE_APPROVED', user_id: userId, record_id: id, linked_expense_id: expenseId });
    await auditLog(userId, 'VendorInvoice', 'APPROVE', id, { status: 'APPROVED', linked_expense_id: expenseId });
    ok(res, updated);
  } catch (e) { next(e); }
});

// ── PATCH /:propertyId/vendor-invoices/:id/pay ────────────────────────────────
// Marks an APPROVED invoice PAID and, on accrual basis, posts the settlement leg to
// the GL: Dr 2100 Accounts Payable / Cr 1100 FCB Bank (…3082) — clearing the payable
// recognised when the linked Finance expense was approved (Dr 5100 / Cr 2100).
// Cross-DB (jag_properties ↔ jag_family); compensating writes, no distributed txn.
//
// The settlement JE is posted ONLY when the linked expense is finance-APPROVED and was
// credited to Accounts Payable. If the expense credited a bank/asset directly (cash
// basis — already settled at approval) or there is no linked expense, the invoice is
// still marked PAID with no second leg. If the linked expense is not yet finance-
// approved, paying is blocked (there is no recognised payable to settle against).

vendorInvoicesRouter.patch('/:id/pay', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const paramParsed = InvoiceParam.safeParse(req.params);
    if (!paramParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Invalid path parameters.'); return; }

    const bodyParsed = PayInvoiceSchema.safeParse(req.body);
    if (!bodyParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Request body validation failed.'); return; }

    const { id, propertyId } = paramParsed.data;
    const { paid_date, payment_reference } = bodyParsed.data;
    const { ownerId, userId } = req.rlsCtx;

    // ── Step 1 — Load the invoice (must be APPROVED) + its property name ──────────
    const propClient = await propertiesPool.connect();
    let invoice: {
      linked_expense_id: string | null; vendor_name: string;
      invoice_ref: string | null; property_name: string;
    } | null;
    try {
      invoice = await withOwnerRLS(propClient, req.rlsCtx, (c) =>
        c.query(
          `SELECT vi.linked_expense_id, vi.vendor_name, vi.invoice_ref,
                  COALESCE(p.name, p.address_line1, 'Property') AS property_name
           FROM   prop_vendor_invoices vi
           JOIN   prop_properties p ON p.id = vi.property_id
           WHERE  vi.id = $1 AND vi.property_id = $2 AND vi.status = 'APPROVED'`,
          [id, propertyId],
        ).then(r => r.rows[0] ?? null),
      );
    } finally { propClient.release(); }

    if (!invoice) { err(res, 404, 'INVOICE_NOT_FOUND', 'Invoice not found or not in APPROVED status.'); return; }

    // ── Step 2 — Cross-DB: post the settlement leg if a payable is outstanding ────
    const idemKey = `prop-invoice-pay-${id}`;
    let settlementJeId: string | null = null;
    let settlementCreated = false;

    if (invoice.linked_expense_id) {
      const famClient = await familyPool.connect();
      try {
        const outcome = await withOwnerRLS(famClient, req.rlsCtx, async (c) => {
          const exp = await c.query<{
            id: string; status: string; amount_ttd: string;
            gl_credit_account_id: string | null; owner_entity_id: string;
          }>(
            `SELECT id, status, amount_ttd, gl_credit_account_id, owner_entity_id
             FROM   fin_expenses WHERE id = $1`,
            [invoice!.linked_expense_id],
          ).then(r => r.rows[0] ?? null);

          // Linked expense missing (deleted) — nothing to settle; allow a plain pay.
          if (!exp) return { blocked: false as const, je: null as string | null, created: false };

          // Not yet finance-approved → no payable was recognised; block paying.
          if (exp.status !== 'APPROVED') return { blocked: true as const, je: null, created: false };

          // Resolve the Properties entity's A/P (2100) and Bank (1100) accounts.
          const accts = await c.query<{ account_code: string; id: string }>(
            `SELECT account_code, id FROM fin_gl_accounts
             WHERE owner_entity_id = $1 AND account_code = ANY($2::text[]) AND is_active = true`,
            [exp.owner_entity_id, [AP_ACCOUNT_CODE, BANK_ACCOUNT_CODE]],
          );
          const apId   = accts.rows.find(a => a.account_code === AP_ACCOUNT_CODE)?.id ?? null;
          const bankId = accts.rows.find(a => a.account_code === BANK_ACCOUNT_CODE)?.id ?? null;

          // Only settle when the expense was credited to A/P (accrual). If it was
          // credited to a bank/asset directly (cash basis) the payable was never
          // raised — it is already settled — so skip the second leg.
          if (!apId || !bankId || exp.gl_credit_account_id !== apId) {
            return { blocked: false as const, je: null, created: false };
          }

          // Settle the exact amount that was accrued (guarantees A/P nets to zero).
          const amountTtd = Number(exp.amount_ttd).toFixed(2);
          const desc = `Vendor payment — ${invoice!.vendor_name}`
            + `${invoice!.invoice_ref ? ' #' + invoice!.invoice_ref : ''} (${invoice!.property_name})`;

          const je = await c.query<{ id: string }>(
            `INSERT INTO fin_journal_entries
               (owner_id, owner_entity_id, entry_date, description, status, source, source_id,
                currency, total_debit_ttd, total_credit_ttd, posted_at, posted_by, idempotency_key)
             VALUES ($1,$2,$3,$4,'POSTED','MANUAL',$5,'TTD',$6,$6,now(),$1,$7)
             ON CONFLICT (idempotency_key) DO NOTHING
             RETURNING id`,
            [ownerId, exp.owner_entity_id, paid_date, desc, exp.id, amountTtd, idemKey],
          );

          // Settlement JE already exists from a prior partial run — reuse it.
          if (!je.rows[0]) {
            const existing = await c.query<{ id: string }>(
              `SELECT id FROM fin_journal_entries WHERE idempotency_key = $1`, [idemKey],
            );
            return { blocked: false as const, je: existing.rows[0].id, created: false };
          }

          // Dr Accounts Payable, Cr Bank.
          await c.query(
            `INSERT INTO fin_journal_entry_lines
               (owner_id, journal_entry_id, gl_account_id, line_number, description, debit_ttd, credit_ttd)
             VALUES ($1,$2,$3,1,$4,$5,0), ($1,$2,$6,2,$4,0,$5)`,
            [ownerId, je.rows[0].id, apId, desc, amountTtd, bankId],
          );
          return { blocked: false as const, je: je.rows[0].id, created: true };
        });

        if (outcome.blocked) {
          err(res, 409, 'EXPENSE_NOT_APPROVED',
            'The linked Finance expense must be approved before this invoice can be paid.');
          return;
        }
        settlementJeId    = outcome.je;
        settlementCreated = outcome.created;
      } catch (e) {
        logger.error({ entity: 'PROPERTIES', action: 'VENDOR_INVOICE_SETTLEMENT_FAILED', record_id: id, error: String(e) });
        err(res, 502, 'FINANCE_SETTLEMENT_FAILED', 'Could not post the payment to the ledger; invoice left unpaid.');
        return;
      } finally { famClient.release(); }
    }

    // ── Step 3 — Mark the invoice PAID + record the settlement link (guarded) ─────
    const propClient2 = await propertiesPool.connect();
    let updated: Record<string, unknown> | null;
    try {
      updated = await withOwnerRLS(propClient2, req.rlsCtx, (c) =>
        c.query(
          `UPDATE prop_vendor_invoices
           SET    status                      = 'PAID',
                  paid_date                   = $1,
                  payment_reference           = $2,
                  settlement_journal_entry_id = $3,
                  updated_at                  = now()
           WHERE  id = $4
             AND  property_id = $5
             AND  status = 'APPROVED'
           RETURNING *`,
          [paid_date, payment_reference ?? null, settlementJeId, id, propertyId],
        ).then(r => r.rows[0] ?? null),
      );
    } finally { propClient2.release(); }

    // Race: invoice left APPROVED between step 1 and step 3. Compensate by removing the
    // settlement JE we just created (only if this call created it — never a prior one).
    if (!updated) {
      if (settlementCreated && settlementJeId) {
        const cleanup = await familyPool.connect();
        try {
          await withOwnerRLS(cleanup, req.rlsCtx, async (c) => {
            await c.query(`DELETE FROM fin_journal_entry_lines WHERE journal_entry_id = $1`, [settlementJeId]);
            await c.query(`DELETE FROM fin_journal_entries WHERE id = $1 AND status = 'POSTED'`, [settlementJeId]);
          });
        } catch (e) {
          logger.warn({ entity: 'PROPERTIES', action: 'VENDOR_INVOICE_SETTLEMENT_CLEANUP_FAILED', record_id: id, je_id: settlementJeId, error: String(e) });
        } finally { cleanup.release(); }
      }
      err(res, 409, 'INVOICE_STATE_CHANGED', 'Invoice was modified concurrently; please retry.');
      return;
    }

    logger.info({ entity: 'PROPERTIES', action: 'VENDOR_INVOICE_PAID', user_id: userId, record_id: id, settlement_journal_entry_id: settlementJeId });
    await auditLog(userId, 'VendorInvoice', 'PAY', id, { paid_date, payment_reference, settlement_journal_entry_id: settlementJeId });
    ok(res, updated);
  } catch (e) { next(e); }
});

// ── PATCH /:propertyId/vendor-invoices/:id/unpay ──────────────────────────────
// Undoes a payment made in error: reverts PAID → APPROVED and, if a settlement leg
// was posted, reverses it on the GL with a fresh entry — Dr 1100 FCB Bank / Cr 2100
// Accounts Payable (the exact opposite of the original settlement). The original
// settlement entry is left POSTED (untouched) — the cash movement it recorded really
// happened; the reversing entry is what restores the payable and the bank balance,
// preserving full history of both the payment and its later reversal. Owner only.
// Cross-DB (jag_properties ↔ jag_family); compensating writes, no distributed txn.

vendorInvoicesRouter.patch('/:id/unpay', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    if (!req.rlsCtx.isOwner) { err(res, 403, 'FORBIDDEN', 'Only the Owner can unpay an invoice.'); return; }

    const paramParsed = InvoiceParam.safeParse(req.params);
    if (!paramParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Invalid path parameters.'); return; }

    const bodyParsed = UnpayInvoiceSchema.safeParse(req.body);
    if (!bodyParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'reason is required.'); return; }

    const { id, propertyId } = paramParsed.data;
    const { reason } = bodyParsed.data;
    const { ownerId, userId } = req.rlsCtx;

    // ── Step 1 — Load the invoice (must be PAID) + its property name ──────────────
    const propClient = await propertiesPool.connect();
    let invoice: {
      settlement_journal_entry_id: string | null; vendor_name: string;
      invoice_ref: string | null; property_name: string;
    } | null;
    try {
      invoice = await withOwnerRLS(propClient, req.rlsCtx, (c) =>
        c.query(
          `SELECT vi.settlement_journal_entry_id, vi.vendor_name, vi.invoice_ref,
                  COALESCE(p.name, p.address_line1, 'Property') AS property_name
           FROM   prop_vendor_invoices vi
           JOIN   prop_properties p ON p.id = vi.property_id
           WHERE  vi.id = $1 AND vi.property_id = $2 AND vi.status = 'PAID'`,
          [id, propertyId],
        ).then(r => r.rows[0] ?? null),
      );
    } finally { propClient.release(); }

    if (!invoice) { err(res, 404, 'INVOICE_NOT_FOUND', 'Invoice not found or not in PAID status.'); return; }

    // ── Step 2 — Cross-DB: reverse the settlement leg, if one was posted ──────────
    const idemKey = `prop-invoice-unpay-${id}`;
    let reversalJeId: string | null = null;
    let reversalCreated = false;

    if (invoice.settlement_journal_entry_id) {
      const famClient = await familyPool.connect();
      try {
        ({ reversalJeId, reversalCreated } = await withOwnerRLS(famClient, req.rlsCtx, async (c) => {
          const original = await c.query<{
            id: string; owner_entity_id: string; entry_date: string;
          }>(
            `SELECT id, owner_entity_id, entry_date::text FROM fin_journal_entries WHERE id = $1 AND status = 'POSTED'`,
            [invoice!.settlement_journal_entry_id],
          ).then(r => r.rows[0] ?? null);

          // Original settlement JE missing or already voided — nothing to reverse.
          if (!original) return { reversalJeId: null, reversalCreated: false };

          const lines = await c.query<{ gl_account_id: string; debit_ttd: string; credit_ttd: string }>(
            `SELECT gl_account_id, debit_ttd, credit_ttd FROM fin_journal_entry_lines
             WHERE journal_entry_id = $1 ORDER BY line_number`,
            [original.id],
          ).then(r => r.rows);

          const totalTtd = lines.reduce((s, l) => s + Number(l.debit_ttd), 0).toFixed(2);
          const desc = `Vendor payment reversal — ${invoice!.vendor_name}`
            + `${invoice!.invoice_ref ? ' #' + invoice!.invoice_ref : ''} (${invoice!.property_name}): ${reason}`;

          const je = await c.query<{ id: string }>(
            `INSERT INTO fin_journal_entries
               (owner_id, owner_entity_id, entry_date, description, status, source, source_id,
                currency, total_debit_ttd, total_credit_ttd, posted_at, posted_by, idempotency_key)
             VALUES ($1,$2,CURRENT_DATE,$3,'POSTED','REVERSAL',$4,'TTD',$5,$5,now(),$1,$6)
             ON CONFLICT (idempotency_key) DO NOTHING
             RETURNING id`,
            [ownerId, original.owner_entity_id, desc, original.id, totalTtd, idemKey],
          );

          if (!je.rows[0]) {
            const existing = await c.query<{ id: string }>(
              `SELECT id FROM fin_journal_entries WHERE idempotency_key = $1`, [idemKey],
            );
            return { reversalJeId: existing.rows[0].id, reversalCreated: false };
          }

          // Swap debit/credit of every original line.
          for (let i = 0; i < lines.length; i++) {
            await c.query(
              `INSERT INTO fin_journal_entry_lines
                 (owner_id, journal_entry_id, gl_account_id, line_number, description, debit_ttd, credit_ttd)
               VALUES ($1,$2,$3,$4,$5,$6,$7)`,
              [ownerId, je.rows[0].id, lines[i].gl_account_id, i + 1, desc, lines[i].credit_ttd, lines[i].debit_ttd],
            );
          }
          return { reversalJeId: je.rows[0].id, reversalCreated: true };
        }));
      } catch (e) {
        logger.error({ entity: 'PROPERTIES', action: 'VENDOR_INVOICE_UNPAY_FAILED', record_id: id, error: String(e) });
        err(res, 502, 'FINANCE_REVERSAL_FAILED', 'Could not reverse the payment on the ledger; invoice left paid.');
        return;
      } finally { famClient.release(); }
    }

    // ── Step 3 — Revert the invoice to APPROVED (guarded) ─────────────────────────
    const propClient2 = await propertiesPool.connect();
    let updated: Record<string, unknown> | null;
    try {
      updated = await withOwnerRLS(propClient2, req.rlsCtx, (c) =>
        c.query(
          `UPDATE prop_vendor_invoices
           SET    status                      = 'APPROVED',
                  paid_date                   = NULL,
                  payment_reference           = NULL,
                  settlement_journal_entry_id = NULL,
                  updated_at                  = now()
           WHERE  id = $1
             AND  property_id = $2
             AND  status = 'PAID'
           RETURNING *`,
          [id, propertyId],
        ).then(r => r.rows[0] ?? null),
      );
    } finally { propClient2.release(); }

    // Race: invoice left PAID between step 1 and step 3. Compensate by removing the
    // reversal JE we just created (only if this call created it).
    if (!updated) {
      if (reversalCreated && reversalJeId) {
        const cleanup = await familyPool.connect();
        try {
          await withOwnerRLS(cleanup, req.rlsCtx, async (c) => {
            await c.query(`DELETE FROM fin_journal_entry_lines WHERE journal_entry_id = $1`, [reversalJeId]);
            await c.query(`DELETE FROM fin_journal_entries WHERE id = $1 AND status = 'POSTED'`, [reversalJeId]);
          });
        } catch (e) {
          logger.warn({ entity: 'PROPERTIES', action: 'VENDOR_INVOICE_UNPAY_CLEANUP_FAILED', record_id: id, je_id: reversalJeId, error: String(e) });
        } finally { cleanup.release(); }
      }
      err(res, 409, 'INVOICE_STATE_CHANGED', 'Invoice was modified concurrently; please retry.');
      return;
    }

    logger.info({ entity: 'PROPERTIES', action: 'VENDOR_INVOICE_UNPAID', user_id: userId, record_id: id, reversal_journal_entry_id: reversalJeId });
    await auditLog(userId, 'VendorInvoice', 'UNPAY', id, { reason, reversal_journal_entry_id: reversalJeId });
    ok(res, updated);
  } catch (e) { next(e); }
});

// ── GET /:propertyId/vendor-invoices/:id/allocations ──────────────────────────

vendorInvoicesRouter.get('/:id/allocations', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const paramParsed = InvoiceParam.safeParse(req.params);
    if (!paramParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Invalid path parameters.'); return; }
    const { id, propertyId } = paramParsed.data;

    const client = await propertiesPool.connect();
    try {
      const rows = await withOwnerRLS(client, req.rlsCtx, (c) =>
        c.query(
          `SELECT a.id, a.invoice_id, a.unit_id, a.pct, a.amount, a.created_at, u.unit_number
           FROM   prop_vendor_invoice_allocations a
           JOIN   prop_units u ON u.id = a.unit_id
           JOIN   prop_vendor_invoices i ON i.id = a.invoice_id
           WHERE  a.invoice_id = $1 AND i.property_id = $2
           ORDER  BY u.unit_number`,
          [id, propertyId],
        ).then(r => r.rows),
      );
      ok(res, rows);
    } finally { client.release(); }
  } catch (e) { next(e); }
});

// ── POST /:propertyId/vendor-invoices/:id/allocations — replace allocation set ─

vendorInvoicesRouter.post('/:id/allocations', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const paramParsed = InvoiceParam.safeParse(req.params);
    if (!paramParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Invalid path parameters.'); return; }
    const bodyParsed = AllocateSchema.safeParse(req.body);
    if (!bodyParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Request body validation failed.'); return; }

    const { id, propertyId } = paramParsed.data;
    const body = bodyParsed.data;
    const { userId: ownerId } = req.rlsCtx;

    let unitIds: string[];
    let pcts: number[];
    if (body.method === 'EQUAL') {
      unitIds = body.unit_ids;
      pcts = unitIds.map(() => 100 / unitIds.length);
    } else {
      unitIds = body.allocations.map(a => a.unit_id);
      pcts = body.allocations.map(a => a.pct);
      const pctSum = pcts.reduce((s, p) => s + p, 0);
      if (Math.abs(pctSum - 100) > 0.5) {
        err(res, 422, 'VALIDATION_ERROR', `Percentages must sum to 100 (got ${pctSum.toFixed(2)}).`);
        return;
      }
    }
    if (new Set(unitIds).size !== unitIds.length) {
      err(res, 422, 'VALIDATION_ERROR', 'Each unit can only appear once in an allocation.'); return;
    }

    const client = await propertiesPool.connect();
    try {
      const result = await withOwnerRLS(client, req.rlsCtx, async (c) => {
        const invoice = await c.query<{ amount: string }>(
          `SELECT amount FROM prop_vendor_invoices WHERE id = $1 AND property_id = $2`,
          [id, propertyId],
        ).then(r => r.rows[0] ?? null);
        if (!invoice) throw Object.assign(new Error('INVOICE_NOT_FOUND'), { httpStatus: 404 });

        const unitCheck = await c.query<{ id: string }>(
          `SELECT id FROM prop_units WHERE id = ANY($1::uuid[]) AND property_id = $2`,
          [unitIds, propertyId],
        );
        if (unitCheck.rows.length !== unitIds.length) {
          throw Object.assign(new Error('UNIT_NOT_IN_PROPERTY'), { httpStatus: 422 });
        }

        const amounts = distributeByPct(Number(invoice.amount), pcts);

        await c.query(`DELETE FROM prop_vendor_invoice_allocations WHERE invoice_id = $1`, [id]);

        const inserted = [];
        for (let i = 0; i < unitIds.length; i++) {
          const row = await c.query(
            `INSERT INTO prop_vendor_invoice_allocations (owner_id, invoice_id, unit_id, pct, amount)
             VALUES ($1,$2,$3,$4,$5) RETURNING id, invoice_id, unit_id, pct, amount, created_at`,
            [ownerId, id, unitIds[i], pcts[i], amounts[i]],
          );
          inserted.push(row.rows[0]);
        }
        return inserted;
      });

      logger.info({ entity: 'PROPERTIES', action: 'VENDOR_INVOICE_ALLOCATED', user_id: ownerId, record_id: id, unit_count: unitIds.length });
      await auditLog(ownerId, 'VendorInvoice', 'ALLOCATE', id, { method: body.method, unit_ids: unitIds });
      ok(res, result, 201);
    } finally { client.release(); }
  } catch (e: unknown) {
    const ex = e as { httpStatus?: number; message: string };
    if (ex.httpStatus === 404) { err(res, 404, 'INVOICE_NOT_FOUND', 'Invoice not found.'); return; }
    if (ex.httpStatus === 422) { err(res, 422, 'VALIDATION_ERROR', 'One or more units do not belong to this property.'); return; }
    next(e);
  }
});

// ── DELETE /:propertyId/vendor-invoices/:id/allocations ────────────────────────

vendorInvoicesRouter.delete('/:id/allocations', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const paramParsed = InvoiceParam.safeParse(req.params);
    if (!paramParsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Invalid path parameters.'); return; }
    const { id, propertyId } = paramParsed.data;
    const { userId: ownerId } = req.rlsCtx;

    const client = await propertiesPool.connect();
    try {
      const deleted = await withOwnerRLS(client, req.rlsCtx, (c) =>
        c.query(
          `DELETE FROM prop_vendor_invoice_allocations
           WHERE invoice_id = $1
             AND invoice_id IN (SELECT id FROM prop_vendor_invoices WHERE id = $1 AND property_id = $2)
           RETURNING id`,
          [id, propertyId],
        ).then(r => r.rows),
      );
      logger.info({ entity: 'PROPERTIES', action: 'VENDOR_INVOICE_ALLOCATIONS_CLEARED', user_id: ownerId, record_id: id, count: deleted.length });
      ok(res, { invoice_id: id, cleared: deleted.length });
    } finally { client.release(); }
  } catch (e) { next(e); }
});
