// GET  /api/v1/ims/movements
// POST /api/v1/ims/movements

import { Router, type Request, type Response, type NextFunction } from 'express';
import { z } from 'zod';
import { withTenantRLS } from '../../middleware/rls';
import { commercialPool, corePool } from '../../db/index';
import { logger } from '../../lib/logger';
import { ok, err } from '../../lib/response';

export const imsMovementsRouter = Router();

// ── Schemas ───────────────────────────────────────────────────────────────────

const MovementTypeEnum = z.enum(['RECEIVE', 'TRANSFER', 'ADJUSTMENT', 'CONSUME', 'RETURN', 'DISPOSAL', 'SALE']);

const MovementsQuerySchema = z.object({
  item_id:       z.string().uuid().optional(),
  movement_type: MovementTypeEnum.optional(),
  page:          z.coerce.number().int().min(1).default(1),
  limit:         z.coerce.number().int().min(1).max(100).default(20),
}).strict();

const CreateMovementSchema = z.object({
  item_id:          z.string().uuid(),
  movement_type:    MovementTypeEnum,
  quantity:         z.number().positive('Quantity must be a positive number.'),
  from_location_id: z.string().uuid().optional(),
  to_location_id:   z.string().uuid().optional(),
  reference_type:   z.string().max(50).optional(),
  reference_id:     z.string().uuid().optional(),
  notes:            z.string().max(1000).optional(),
  idempotency_key:  z.string().uuid('idempotency_key must be a UUID generated by the client.'),
  // SALE-only fields
  sale_price:       z.number().positive().optional(),
  customer_name:    z.string().max(200).optional(),
  internal_entity:  z.string().uuid().optional(),
}).strict().superRefine((data, ctx) => {
  if (data.movement_type === 'TRANSFER' && !data.to_location_id) {
    ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'to_location_id is required for TRANSFER movements.', path: ['to_location_id'] });
  }
  if (data.movement_type === 'SALE' && data.sale_price === undefined) {
    ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'sale_price is required for SALE movements.', path: ['sale_price'] });
  }
  if (data.movement_type !== 'SALE' && (data.sale_price !== undefined || data.customer_name !== undefined || data.internal_entity !== undefined)) {
    ctx.addIssue({ code: z.ZodIssueCode.custom, message: 'sale_price, customer_name, and internal_entity are only valid for SALE movements.', path: ['movement_type'] });
  }
});

// ── GET /movements ────────────────────────────────────────────────────────────

imsMovementsRouter.get('/', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const parsed = MovementsQuerySchema.safeParse(req.query);
    if (!parsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Invalid query parameters.'); return; }

    const { item_id, movement_type, page, limit } = parsed.data;
    const offset = (page - 1) * limit;

    const client = await commercialPool.connect();
    try {
      const { rows, total } = await withTenantRLS(client, req.rlsCtx, async (c) => {
        const conditions: string[] = [];
        const params: unknown[] = [];
        const push = (v: unknown) => { params.push(v); return `$${params.length}`; };

        if (item_id)       conditions.push(`m.item_id = ${push(item_id)}`);
        if (movement_type) conditions.push(`m.movement_type = ${push(movement_type)}`);
        const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : '';

        const countResult = await c.query<{ count: string }>(
          `SELECT count(*) FROM ims_stock_movements m ${where}`,
          params,
        );

        const dataResult = await c.query(
          `SELECT m.id, m.item_id, m.movement_type, m.quantity,
                  m.from_location_id, fl.name AS from_location_name,
                  m.to_location_id,   tl.name AS to_location_name,
                  i.name AS item_name, i.sku, i.vat_code,
                  m.sale_price, m.vat_amount, m.customer_name, m.internal_entity,
                  m.reference_type, m.reference_id, m.notes,
                  m.performed_by, m.idempotency_key,
                  m.last_modified_at, m.created_at
           FROM   ims_stock_movements m
           JOIN   ims_items i ON i.id = m.item_id
           LEFT JOIN ims_locations fl ON fl.id = m.from_location_id
           LEFT JOIN ims_locations tl ON tl.id = m.to_location_id
           ${where}
           ORDER BY m.created_at DESC
           LIMIT  ${push(limit)} OFFSET ${push(offset)}`,
          params,
        );

        return { rows: dataResult.rows, total: Number(countResult.rows[0].count) };
      });

      logger.info({ entity: 'IMS', action: 'MOVEMENTS_LIST', user_id: req.rlsCtx.userId, tenant_id: req.rlsCtx.tenantId, count: rows.length });
      ok(res, { movements: rows, pagination: { page, limit, total, pages: Math.ceil(total / limit) } });
    } finally { client.release(); }
  } catch (e) { next(e); }
});

// ── POST /movements ───────────────────────────────────────────────────────────
//
// OFFLINE-CRITICAL: client generates idempotency_key offline before submitting.
// On reconnect, re-posting the same key returns 200 with the original record
// instead of 201 — never 409 (STD-11).
//
// Side-effects applied within the SAME transaction as the movement insert:
//   RECEIVE | RETURN      → quantity_on_hand += quantity
//   CONSUME | DISPOSAL    → quantity_on_hand -= quantity
//   ADJUSTMENT            → quantity_on_hand += quantity (client sends signed value for decrements)
//   TRANSFER              → item.location_id = to_location_id

imsMovementsRouter.post('/', async (req: Request, res: Response, next: NextFunction): Promise<void> => {
  try {
    const parsed = CreateMovementSchema.safeParse(req.body);
    if (!parsed.success) { err(res, 422, 'VALIDATION_ERROR', 'Request body validation failed.'); return; }

    const body = parsed.data;
    const { userId, tenantId } = req.rlsCtx;

    const client = await commercialPool.connect();
    try {
      const { movement, created } = await withTenantRLS(client, req.rlsCtx, async (c) => {
        // STD-11: check idempotency key first.
        const existing = await c.query<{ id: string }>(
          `SELECT id FROM ims_stock_movements WHERE idempotency_key = $1`,
          [body.idempotency_key],
        );
        if (existing.rows.length > 0) {
          // Duplicate delivery — fetch and return original record.
          const dup = await c.query(
            `SELECT m.*, i.name AS item_name
             FROM   ims_stock_movements m JOIN ims_items i ON i.id = m.item_id
             WHERE  m.id = $1`,
            [existing.rows[0].id],
          );
          return { movement: dup.rows[0], created: false };
        }

        // Verify item exists and belongs to this tenant (RLS enforces tenant scope).
        const itemCheck = await c.query<{ id: string; quantity_on_hand: number; location_id: string; vat_code: string }>(
          `SELECT id, quantity_on_hand, location_id, vat_code FROM ims_items WHERE id = $1`,
          [body.item_id],
        );
        if (itemCheck.rows.length === 0) {
          throw Object.assign(new Error('ITEM_NOT_FOUND'), { httpStatus: 404 });
        }

        // Compute VAT for SALE movements only.
        // STANDARD = 12.5% (TT VAT rate); ZERO and EXEMPT = 0.
        let vatAmount: number | null = null;
        if (body.movement_type === 'SALE' && body.sale_price !== undefined) {
          const vatRate = itemCheck.rows[0].vat_code === 'STANDARD' ? 0.125 : 0;
          vatAmount = Math.round(body.sale_price * body.quantity * vatRate * 100) / 100;
        }

        // Insert movement record.
        const movement = await c.query(
          `INSERT INTO ims_stock_movements
             (tenant_id, item_id, from_location_id, to_location_id,
              quantity, movement_type, reference_type, reference_id,
              notes, performed_by, idempotency_key,
              sale_price, vat_amount, customer_name, internal_entity)
           VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
           RETURNING *`,
          [
            tenantId,
            body.item_id,
            body.from_location_id ?? null,
            body.to_location_id   ?? null,
            body.quantity,
            body.movement_type,
            body.reference_type   ?? null,
            body.reference_id     ?? null,
            body.notes            ?? null,
            userId,
            body.idempotency_key,
            body.sale_price       ?? null,
            vatAmount,
            body.customer_name    ?? null,
            body.internal_entity  ?? null,
          ],
        );

        // Apply quantity / location side-effects in the same transaction.
        if (['RECEIVE', 'RETURN'].includes(body.movement_type)) {
          await c.query(
            `UPDATE ims_items SET quantity_on_hand = quantity_on_hand + $1,
                    last_modified_at = now(), last_modified_by = $2, updated_at = now()
             WHERE id = $3`,
            [body.quantity, userId, body.item_id],
          );
        } else if (['CONSUME', 'DISPOSAL', 'SALE'].includes(body.movement_type)) {
          await c.query(
            `UPDATE ims_items SET quantity_on_hand = quantity_on_hand - $1,
                    last_modified_at = now(), last_modified_by = $2, updated_at = now()
             WHERE id = $3`,
            [body.quantity, userId, body.item_id],
          );
        } else if (body.movement_type === 'ADJUSTMENT') {
          // quantity may be negative for a downward adjustment.
          await c.query(
            `UPDATE ims_items SET quantity_on_hand = quantity_on_hand + $1,
                    last_modified_at = now(), last_modified_by = $2, updated_at = now()
             WHERE id = $3`,
            [body.quantity, userId, body.item_id],
          );
        } else if (body.movement_type === 'TRANSFER' && body.to_location_id) {
          await c.query(
            `UPDATE ims_items SET location_id = $1,
                    last_modified_at = now(), last_modified_by = $2, updated_at = now()
             WHERE id = $3`,
            [body.to_location_id, userId, body.item_id],
          );
        }

        return { movement: movement.rows[0], created: true };
      });

      // If we surfaced a domain error (404), re-throw after pool release.
      const movementRow = movement as Record<string, unknown> & { httpStatus?: number };
      if (movementRow.httpStatus === 404) {
        err(res, 404, 'ITEM_NOT_FOUND', 'Item not found.'); return;
      }

      logger.info({
        entity:    'IMS',
        action:    created ? 'MOVEMENT_CREATED' : 'MOVEMENT_DUPLICATE',
        user_id:   userId,
        tenant_id: tenantId,
        record_id: (movement as { id: string }).id,
      });

      // Audit log — best-effort via corePool.
      if (created) {
        const coreClient = await corePool.connect();
        try {
          await coreClient.query('BEGIN');
          await coreClient.query('SELECT set_config($1, $2, true)', ['app.current_tenant_id', tenantId]);
          await coreClient.query('SELECT set_config($1, $2, true)', ['app.current_user_id', userId]);
          await coreClient.query(
            `INSERT INTO audit_log (tenant_id, user_id, entity, action, record_id, new_values, source)
             VALUES ($1, $2, 'StockMovement', 'CREATE', $3, $4, 'API')`,
            [tenantId, userId, (movement as { id: string }).id, JSON.stringify(body)],
          );
          await coreClient.query('COMMIT');
        } catch (auditErr) {
          await coreClient.query('ROLLBACK');
          logger.warn({ entity: 'IMS', action: 'AUDIT_LOG_FAILED', error_message: (auditErr as Error).message });
        } finally { coreClient.release(); }
      }

      ok(res, movement, created ? 201 : 200);
    } finally { client.release(); }
  } catch (e) { next(e); }
});
