-- Migration 014: expand transaction category CHECK constraint
-- Adds: GROCERIES, FUEL, DINING, HARDWARE, LOAN_PAYMENT

ALTER TABLE fin_transactions
  DROP CONSTRAINT IF EXISTS fin_transactions_category_check;

ALTER TABLE fin_transactions
  ADD CONSTRAINT fin_transactions_category_check
  CHECK (category IN (
    'SALARY','DIVIDEND','RENTAL_INCOME','INTEREST_INCOME','TRANSFER_IN',
    'OPERATING_EXPENSE','PAYROLL','TAX_PAYMENT','LOAN_REPAYMENT',
    'INVESTMENT_PURCHASE','INVESTMENT_SALE','TRANSFER_OUT',
    'PERSONAL_EXPENSE','UTILITIES','INSURANCE','ENTERTAINMENT',
    'TRAVEL','MEDICAL','EDUCATION','CHARITY',
    'GROCERIES','FUEL','DINING','HARDWARE','LOAN_PAYMENT',
    'UNCLASSIFIED'
  ));
